// Guides — answer-first, experience-based, each routing to the relevant money page. Volatile numbers avoided.
const U = '2026-09-16'
export const GUIDES = [
  {
    slug: 'what-is-real-estate-development', cta: 'project', updated: U,
    related: { services: ['real-estate-development', 'land-brokerage'], areas: ['sharon-region', 'hod-hasharon'], guides: ['rezoning-process', 'developer-vs-contractor', 'construction-supervision', 'land-due-diligence-checklist'], glossary: ['developer', 'taba', 'building-permit', 'combination-deal', 'building-rights', 'local-committee'] },
    he: {
      h1: 'מה זה יזמות נדל"ן ואיך פרויקט נדל"ן מתחיל — כל השלבים',
      metaTitle: 'יזמות נדל"ן: מה זה, איך מתחילים ומהם שלבי הפרויקט | אפיק הנחל',
      description: 'מדריך ברור ליזמות נדל"ן בישראל: מה עושה יזם, איך פרויקט מתחיל מקרקע, מהם 10 שלבי הפרויקט — מאיתור ובדיקות תכנוניות, דרך שינוי ייעוד, רישוי ומימון, ועד ביצוע, שיווק ומסירה.',
      summary: 'יזמות נדל"ן היא הובלת פרויקט מהרעיון ועד המוצר המוגמר: היזם מאתר קרקע או נכס עם פוטנציאל, בודק מה מותר לבנות, מקדם תכנון ורישוי, מארגן מימון וביצוע, ומשווק את התוצר — ונושא בסיכון ובאחריות לאורך כל הדרך. פרויקט טיפוסי עובר עשרה שלבים, ומשך הזמן מאיתור ועד מסירה נמדד בדרך כלל בשנים.',
      sections: [
        { h2: 'מה עושה יזם נדל"ן', paras: ['היזם הוא בעל הפרויקט. הוא לא בהכרח בונה בעצמו (לזה יש קבלן) ולא מתכנן בעצמו (לזה יש אדריכל), אבל הוא זה שמחליט, מממן, נושא בסיכון ומרוויח מהפער בין העלות הכוללת לשווי המוגמר. יזמות טובה מתחילה הרבה לפני הבנייה — בבחירת הקרקע הנכונה ובהבנה מדויקת של מה מותר לבנות עליה.'] },
        { h2: 'עשרת שלבי פרויקט נדל"ן', steps: [
          '**איתור הקרקע** — מציאת קרקע או נכס שמתאימים למטרה: מגורים, מסחר, התחדשות. בשרון, רוב ההזדמנויות הן קרקעות פרטיות בשולי הערים.',
          '**בדיקות תכנוניות ומשפטיות** — נסח טאבו, בעלות ושעבודים, תב"ע בתוקף, ייעוד, זכויות בנייה, מגבלות (שימור, תשתיות, שטחים פתוחים). כאן נופלים רוב הפרויקטים הגרועים.',
          '**בדיקת היתכנות כלכלית** — עלות קרקע, מיסוי (מס רכישה, מס שבח למוכר, היטל השבחה), תכנון, בנייה, מימון ושיווק מול השווי הצפוי.',
          '**מבנה העסקה** — רכישה, עסקת קומבינציה עם בעל הקרקע, שותפות או קבוצת רכישה.',
          '**תכנון** — אדריכל, יועצים (קונסטרוקציה, תנועה, איכות סביבה) ותוכנית שמתאימה לתב"ע או תוכנית חדשה.',
          '**שינוי ייעוד או הגדלת זכויות (אם נדרש)** — הליך מול הוועדה המקומית או המחוזית, כולל הפקדה, התנגדויות ואישור. תהליך של שנים.',
          '**רישוי** — היתר בנייה מהוועדה המקומית, לאחר עמידה בדרישות ותשלום היטלים ואגרות.',
          '**מימון** — הון עצמי, ליווי בנקאי או מימון חוץ-בנקאי, לפי היקף הפרויקט.',
          '**ביצוע** — בחירת קבלן, פיקוח צמוד, בקרת איכות, לוחות זמנים ותקציב.',
          '**שיווק ומסירה** — מכירת היחידות (לעיתים כבר בשלב הפריסייל), רישום הבית המשותף ומסירת הנכסים.',
        ] },
        { h2: 'כמה זמן לוקח פרויקט נדל"ן', paras: ['פרויקט על קרקע עם תב"ע מאושרת יכול להגיע לאכלוס תוך שלוש עד חמש שנים; פרויקט שדורש שינוי ייעוד או תוכנית חדשה עשוי לקחת הרבה יותר, כי שלב התכנון לבדו נמדד בשנים. לכן ההבדל בין קרקע "עם זכויות" לקרקע "עם פוטנציאל" הוא ההבדל המרכזי במחיר ובסיכון.'] },
        { h2: 'איפה בעלי קרקע נכנסים לתמונה', paras: ['רוב הפרויקטים בשרון מתחילים אצל בעל קרקע פרטי — משפחה, יורשים או חקלאי. לבעל הקרקע יש כמה מסלולים: למכור ליזם, להיכנס לעסקת קומבינציה (הקרקע תמורת חלק מהתוצר), לקדם תוכנית בעצמו ולמכור אחרי ההשבחה, או לשלב. הבחירה תלויה בזמן, בסיכון שהוא מוכן לקחת, ובמיסוי של כל מסלול. [אפיק הנחל מייצגת בעלי קרקע](/services/real-estate-development/) מול יזמים וחברות בנייה ומקדמת תוכניות עד העלייה לקרקע.'] },
        { h2: 'שאלות שכדאי לשאול לפני שנכנסים לפרויקט', bullets: ['מה הייעוד היום, ומה מקור הביטחון שאפשר לשנות אותו?', 'מי הבעלים בפועל — האם כל השותפים חתומים?', 'מה המיסוי הכולל של המסלול שנבחר, כולל היטל השבחה?', 'מה קורה אם התוכנית לא מאושרת — מה שווי הקרקע במצבה הנוכחי?', 'מי מנהל ומפקח על הביצוע, ומה מנגנון בקרת התקציב?'] },
      ],
      faq: [
        { q: 'מה זה יזמות נדל"ן?', a: 'יזמות נדל"ן היא הובלת פרויקט נדל"ן מהאיתור ועד המסירה: זיהוי קרקע או נכס עם פוטנציאל, בדיקות תכנוניות וכלכליות, קידום תכנון ורישוי, ארגון מימון וביצוע, ושיווק התוצר. היזם נושא בסיכון ובאחריות הכוללת.' },
        { q: 'איך מתחילים פרויקט נדל"ן?', a: 'מתחילים מהקרקע: בודקים בעלות, תב"ע, ייעוד, זכויות ומגבלות, ואז בודקים היתכנות כלכלית מלאה כולל מיסוי. רק אם המספרים עובדים עוברים למבנה עסקה, תכנון ורישוי.' },
        { q: 'מהם שלבי יזמות נדל"ן?', a: 'איתור קרקע, בדיקות תכנוניות ומשפטיות, היתכנות כלכלית, מבנה עסקה, תכנון, שינוי ייעוד או הגדלת זכויות אם נדרש, רישוי, מימון, ביצוע, ושיווק ומסירה.' },
        { q: 'כמה זמן לוקח פרויקט בנייה?', a: 'על קרקע עם תב"ע מאושרת — לרוב שלוש עד חמש שנים מאיתור ועד אכלוס. כשנדרש שינוי ייעוד, שלב התכנון לבדו יכול להימשך שנים, והמשך הכולל ארוך בהתאם.' },
      ],
    },
    en: {
      h1: 'What is real estate development and how does a project start — all the stages',
      metaTitle: 'Real Estate Development: What It Is, How to Start and the Project Stages | Afik Hanahal',
      description: 'A clear guide to real estate development in Israel: what a developer does, how a project starts from land, the 10 project stages — from sourcing and planning checks, through rezoning, permits and financing, to construction, marketing and delivery.',
      summary: 'Real estate development is leading a project from idea to finished product: the developer finds land or property with potential, checks what may be built, promotes planning and permits, organises financing and construction, and markets the result — carrying the risk and responsibility throughout. A typical project passes ten stages, and the time from sourcing to delivery is usually measured in years.',
      sections: [
        { h2: 'What a developer does', paras: ['The developer owns the project. They do not necessarily build (that is the contractor) or design (that is the architect), but they decide, finance, carry the risk and earn the gap between total cost and finished value. Good development starts long before construction — in choosing the right land and understanding exactly what may be built on it.'] },
        { h2: 'The ten stages of a project', steps: ['**Sourcing land** — finding land or property that fits the purpose. In the Sharon most opportunities are private land at the city edges.', '**Planning and legal checks** — Tabu extract, ownership and liens, valid zoning plan, designation, building rights, constraints. This is where most bad projects fail.', '**Economic feasibility** — land cost, taxation (purchase tax, seller\'s capital gains, betterment levy), planning, construction, financing and marketing versus expected value.', '**Deal structure** — purchase, combination deal with the owner, partnership or purchase group.', '**Design** — architect, consultants and a scheme that fits the zoning plan or a new plan.', '**Rezoning or added rights (if needed)** — a process with the local or district committee including deposit, objections and approval. Years.', '**Permits** — building permit from the local committee after meeting requirements and paying levies and fees.', '**Financing** — equity, bank project financing or non-bank financing by scale.', '**Construction** — contractor selection, close supervision, quality control, schedule and budget.', '**Marketing and delivery** — selling units (often at pre-sale), condominium registration and handover.'] },
        { h2: 'How long a project takes', paras: ['On land with an approved zoning plan, occupancy can come within three to five years; a project requiring rezoning or a new plan can take much longer, since the planning stage alone is measured in years. The difference between land "with rights" and land "with potential" is therefore the central difference in price and risk.'] },
        { h2: 'Where landowners come in', paras: ['Most projects in the Sharon begin with a private landowner — a family, heirs or a farmer. The owner has several paths: sell to a developer, enter a combination deal (land for part of the product), promote a plan and sell after improvement, or combine them. The choice depends on time, appetite for risk and the taxation of each path. [Afik Hanahal represents landowners](/en/services/real-estate-development/) opposite developers and builders and promotes plans up to ground-breaking.'] },
        { h2: 'Questions to ask before entering a project', bullets: ['What is the designation today, and what is the basis for believing it can change?', 'Who actually owns the land — are all partners signed?', 'What is the total taxation of the chosen path, including betterment levy?', 'If the plan is not approved — what is the land worth as is?', 'Who manages and supervises construction, and what is the budget control mechanism?'] },
      ],
      faq: [
        { q: 'What is real estate development?', a: 'Leading a real estate project from sourcing to delivery: identifying land or property with potential, planning and economic checks, promoting planning and permits, organising financing and construction, and marketing the result. The developer carries the overall risk.' },
        { q: 'How do you start a real estate project?', a: 'Start from the land: check ownership, zoning plan, designation, rights and constraints, then run a full economic feasibility including taxation. Only if the numbers work move to deal structure, design and permits.' },
        { q: 'What are the stages of real estate development?', a: 'Sourcing land, planning and legal checks, economic feasibility, deal structure, design, rezoning or added rights if needed, permits, financing, construction, and marketing and delivery.' },
        { q: 'How long does a construction project take?', a: 'On land with an approved zoning plan — usually three to five years from sourcing to occupancy. When rezoning is required, the planning stage alone can take years, extending the total accordingly.' },
      ],
    },
  },
  {
    slug: 'land-due-diligence-checklist', cta: 'land', updated: U,
    related: { services: ['land-brokerage', 'land-investment'], areas: ['sharon-region'], guides: ['agricultural-land-investment', 'rezoning-process', 'what-is-real-estate-development'], glossary: ['tabu', 'taba', 'building-rights', 'caveat', 'private-land', 'purchase-tax', 'betterment-levy', 'appraiser'] },
    he: {
      h1: 'מה בודקים לפני רכישת קרקע — צ\'קליסט של 12 בדיקות',
      metaTitle: 'איך בודקים קרקע לפני רכישה? צ\'קליסט 12 בדיקות חובה | אפיק הנחל',
      description: 'לפני שקונים קרקע או מגרש: 12 בדיקות חובה — נסח טאבו, בעלות ושעבודים, תב"ע וייעוד, זכויות בנייה, תוכניות מתאר, מבנה בעלות (מושע), מגבלות, גישה ותשתיות, מיסוי ומחיר. מה אנחנו בודקים לפני כל עסקה.',
      summary: 'לפני רכישת קרקע בודקים שלושה דברים: **מי הבעלים** (נסח טאבו, שעבודים, הערות אזהרה, מבנה הבעלות), **מה מותר לבנות** (תב"ע, ייעוד, זכויות, תוכניות מתאר, מגבלות) ו**כמה זה באמת עולה** (מיסוי, היטלים, עלויות פיתוח, והשוואה לעסקאות דומות). קרקע שנראית זולה בלי הבדיקות האלה היא כמעט תמיד יקרה.',
      sections: [
        { h2: 'הצ\'קליסט', steps: [
          '**נסח טאבו עדכני** — מי רשום כבעלים, מה גודל החלקה, ואילו הערות רשומות. אם הקרקע אינה בטאבו (רמ"י / חברה משכנת) — אישור זכויות מהגורם המנהל.',
          '**שעבודים, עיקולים והערות אזהרה** — האם יש משכנתא, עיקול, הערת אזהרה לטובת צד שלישי או צו. כל אחד מאלה משנה את העסקה.',
          '**מבנה הבעלות** — חלקה נפרדת בבעלות אחת, או מושע (בעלות משותפת בחלקים בלתי מסוימים) עם שותפים רבים. במושע אין לכם "מגרש" מוגדר עד שיהיה הסכם שיתוף או פרצלציה.',
          '**התב"ע בתוקף וייעוד הקרקע** — מה התוכנית המאושרת אומרת: חקלאי, מגורים, מסחר, שטח פתוח. זה קובע את השווי יותר מכל דבר אחר.',
          '**זכויות בנייה** — כמה יחידות, אחוזי בנייה, מספר קומות, קווי בניין. מופיע בהוראות התוכנית ובמידע התכנוני מהוועדה.',
          '**תוכניות מתאר ותוכניות בהכנה** — האם הקרקע נכללת בתוכנית מתאר ארצית/מחוזית/כוללנית או בתוכנית בהכנה שמשנה את ייעודה. זה מקור ה"פוטנציאל" — או היעדרו.',
          '**מגבלות ותשריטים** — שימור, תשתיות לאומיות (חשמל, גז, מים), רצועות דרך ורכבת, שטחים פתוחים, נחלים, אתרי עתיקות.',
          '**גישה ותשתיות** — האם יש דרך גישה חוקית לחלקה? מים, חשמל, ביוב? ומי משלם על הפיתוח.',
          '**מצב בשטח** — גבולות בפועל מול הרישום, פולשים, שימושים קיימים, מבנים ללא היתר.',
          '**מיסוי והיטלים** — מס רכישה לרוכש; לבעלים העתידי: היטל השבחה בעת מימוש ומס שבח במכירה. חובה לחשב לפני, לא אחרי.',
          '**הערכת שווי והשוואה** — עסקאות דומות באזור (ניתן לבדוק במאגר רשות המסים), ולא "מחיר לפי הפוטנציאל". שמאי מקרקעין עצמאי בעסקאות גדולות.',
          '**המוכר והמתווך** — מי מוכר, למה, והאם יש הסכם תיווך בכתב. הבטחות בעל-פה על שינוי ייעוד אינן שוות דבר.',
        ] },
        { h2: 'סימני אזהרה', bullets: ['"שינוי הייעוד בדרך" בלי מסמך תכנוני שמראה את זה.', 'מחיר נמוך משמעותית מהשוק — לרוב יש סיבה: מושע, מגבלה, או ייעוד שלא ישתנה.', 'לחץ זמן וחתימה על זיכרון דברים לפני בדיקות.', 'מוכר שאינו רשום כבעלים, או שותפים שאינם חתומים.'] },
        { h2: 'כמה זמן לוקחות הבדיקות', paras: ['בדיקה ראשונית (נסח, תב"ע, ייעוד) — ימים. בדיקה מלאה כולל מידע תכנוני מהוועדה, שמאות וייעוץ משפטי — שבועות. זה זול מאוד ביחס למחיר של טעות. [כך אנחנו עובדים](/services/land-brokerage/) בכל עסקת קרקע.'] },
      ],
      faq: [
        { q: 'איך בודקים קרקע לפני רכישה?', a: 'בודקים בעלות (נסח טאבו, שעבודים, הערות אזהרה, מבנה בעלות), תכנון (תב"ע, ייעוד, זכויות בנייה, תוכניות מתאר, מגבלות), מצב בשטח, וכלכלה (מיסוי, היטלים, פיתוח, השוואה לעסקאות). מומלץ להיעזר בעורך דין מקרקעין ובשמאי.' },
        { q: 'איך בודקים זכויות בנייה בקרקע?', a: 'קוראים את הוראות התב"ע החלה על החלקה (זמינות במערכות התכנון הממשלתיות ובוועדה המקומית) ומבקשים מהוועדה המקומית מידע תכנוני לחלקה. ההוראות מגדירות ייעוד, אחוזי בנייה, מספר יחידות, קומות וקווי בניין.' },
        { q: 'מה זה מושע ולמה זה חשוב?', a: 'מושע הוא בעלות משותפת בחלקה בחלקים בלתי מסוימים — כל שותף מחזיק אחוז מהחלקה כולה, לא מגרש מוגדר. עד שאין הסכם שיתוף או פרצלציה, אי אפשר לבנות או למכור "את המגרש שלי". זה משפיע מאוד על השווי ועל הסחירות.' },
      ],
    },
    en: {
      h1: 'What to check before buying land — a 12-point due diligence checklist',
      metaTitle: 'How to Check Land Before Buying: 12 Mandatory Checks | Afik Hanahal',
      description: 'Before buying land or a plot: 12 mandatory checks — Tabu extract, ownership and liens, zoning plan and designation, building rights, master plans, ownership structure (undivided shares), constraints, access and infrastructure, taxation and price.',
      summary: 'Before buying land you check three things: **who owns it** (Tabu extract, liens, caveats, ownership structure), **what may be built** (zoning plan, designation, rights, master plans, constraints) and **what it really costs** (taxes, levies, development costs, comparable deals). Land that looks cheap without these checks is almost always expensive.',
      sections: [
        { h2: 'The checklist', steps: ['**Current Tabu extract** — registered owner, parcel size, registered notes. If not in Tabu (ILA / housing company) — a rights confirmation from the managing body.', '**Liens, attachments and caveats** — mortgage, attachment, caveat for a third party or court order. Each changes the deal.', '**Ownership structure** — a separate parcel with one owner, or undivided shares with many partners. In undivided shares you have no defined "plot" until a sharing agreement or parcellation.', '**Valid zoning plan and designation** — what the approved plan says: agricultural, residential, commercial, open space. This sets value more than anything.', '**Building rights** — units, building percentages, storeys, setbacks. In the plan provisions and the committee\'s planning information.', '**Master plans and plans in preparation** — whether the land falls within a national/district/comprehensive master plan or a plan in preparation changing its designation. This is the source of "potential" — or its absence.', '**Constraints** — conservation, national infrastructure, road and rail corridors, open spaces, streams, antiquities.', '**Access and infrastructure** — legal access road? Water, electricity, sewage? Who pays for development.', '**Condition on site** — actual boundaries versus registration, trespassers, existing uses, unpermitted structures.', '**Taxes and levies** — purchase tax for the buyer; for the future owner: betterment levy on realisation and capital gains on sale. Calculate before, not after.', '**Valuation and comparison** — comparable deals in the area (the Tax Authority\'s database), not "price by potential". An independent appraiser for large deals.', '**Seller and broker** — who is selling, why, and is there a written brokerage agreement. Verbal promises of rezoning are worth nothing.'] },
        { h2: 'Warning signs', bullets: ['"Rezoning is on the way" without a planning document showing it.', 'A price far below market — usually for a reason: undivided shares, a constraint, or a designation that will not change.', 'Time pressure and signing a memorandum before checks.', 'A seller not registered as owner, or partners not signed.'] },
        { h2: 'How long the checks take', paras: ['An initial check (extract, zoning plan, designation) — days. A full check including committee planning information, appraisal and legal advice — weeks. Very cheap relative to the price of a mistake. [This is how we work](/en/services/land-brokerage/) on every land deal.'] },
      ],
      faq: [
        { q: 'How do you check land before buying?', a: 'Check ownership (Tabu extract, liens, caveats, ownership structure), planning (zoning plan, designation, building rights, master plans, constraints), the condition on site, and economics (taxes, levies, development, comparable deals). Use a real estate lawyer and an appraiser.' },
        { q: 'How do you check building rights on land?', a: 'Read the provisions of the zoning plan applying to the parcel (available in the government planning systems and at the local committee) and request planning information for the parcel from the local committee. The provisions define designation, building percentages, units, storeys and setbacks.' },
        { q: 'What are undivided shares and why do they matter?', a: 'Joint ownership of a parcel in undefined shares — each partner holds a percentage of the whole parcel, not a defined plot. Until a sharing agreement or parcellation exists, you cannot build on or sell "my plot". It strongly affects value and marketability.' },
      ],
    },
  },
  {
    slug: 'rezoning-process', cta: 'land', updated: U,
    related: { services: ['real-estate-development', 'land-brokerage'], areas: ['sharon-region', 'hod-hasharon'], guides: ['what-is-real-estate-development', 'agricultural-land-investment', 'land-due-diligence-checklist'], glossary: ['rezoning', 'taba', 'local-committee', 'district-committee', 'vatmal', 'betterment-levy', 'land-thawing'] },
    he: {
      h1: 'שינוי ייעוד קרקע — שלבים, מי מאשר, כמה זמן ומה זה עולה',
      metaTitle: 'שינוי ייעוד קרקע: שלבי התהליך, ועדות, זמנים והיטל השבחה | אפיק הנחל',
      description: 'איך עובד שינוי ייעוד קרקע (למשל מחקלאי למגורים): מי יוזם, מה עובר בוועדה המקומית והמחוזית, שלבי ההפקדה וההתנגדויות, כמה זמן זה לוקח, מה היטל ההשבחה — ומתי זה בכלל ריאלי.',
      summary: 'שינוי ייעוד קרקע הוא אישור תוכנית בניין עיר (תב"ע) חדשה שמחליפה את הייעוד הקיים של הקרקע — למשל מחקלאי למגורים. התהליך עובר בוועדה המקומית ובדרך כלל גם במחוזית: הכנת תוכנית, דיון, הפקדה, התנגדויות, אישור ופרסום. הוא נמשך לרוב שנים, מחייב היטל השבחה בעת המימוש, ורק חלק קטן מהקרקעות החקלאיות בישראל נמצאות בתהליך כזה בפועל.',
      sections: [
        { h2: 'מי יכול ליזום שינוי ייעוד', paras: ['בעל הקרקע (או קבוצת בעלים), יזם בהסכמת הבעלים, הרשות המקומית, או המדינה (למשל דרך תוכניות מתאר ארציות ומחוזיות והוותמ"ל). בפועל, תוכנית פרטית לחלקה בודדת מאושרת לעיתים רחוקות אם היא סותרת את תוכנית המתאר — לכן השלב הראשון הוא לבדוק מה התכנון העליון אומר על האזור.'] },
        { h2: 'שלבי התהליך', steps: [
          '**בדיקת היתכנות** — האם תוכניות המתאר (ארצית, מחוזית, כוללנית עירונית) מאפשרות את השינוי? אם לא — הסיכוי נמוך מאוד.',
          '**הכנת התוכנית** — אדריכל ותכנון עירוני, יועצים (תנועה, סביבה, ניקוז, שמאות), הסכמת הבעלים.',
          '**הגשה ודיון** — בוועדה המקומית; תוכניות מסוימות דורשות את הוועדה המחוזית (למשל שינוי ייעוד של קרקע חקלאית).',
          '**הפקדה** — התוכנית מתפרסמת לציבור לתקופת התנגדויות.',
          '**התנגדויות ודיון בהן** — שכנים, גופים ירוקים, רשויות. הוועדה מכריעה, לעיתים עם שינויים.',
          '**אישור ופרסום למתן תוקף** — מרגע זה הייעוד החדש בתוקף.',
          '**מימוש** — היתרי בנייה, איחוד וחלוקה (פרצלציה) אם נדרש, ותשלום היטל השבחה.',
        ] },
        { h2: 'כמה זמן זה לוקח', paras: ['תוכניות פשוטות בסמכות ועדה מקומית — לעיתים שנה-שנתיים. שינוי ייעוד משמעותי (חקלאי למגורים) — לרוב כמה שנים, ולעיתים הרבה יותר, תלוי בהתנגדויות, בעומס בוועדות ובתיאום עם גופים ממשלתיים. מי שמבטיח "תוך שנה" — כדאי לבקש ממנו מסמכים.'] },
        { h2: 'מה זה עולה', bullets: ['**היטל השבחה** — הרשות גובה מבעל הקרקע מחצית מעליית השווי שנבעה מהתוכנית, בעת המימוש (מכירה או היתר). זה הסעיף הגדול.', '**עלויות תכנון** — אדריכל, יועצים, שמאי, עורך דין.', '**אגרות ותשלומי פיתוח** — בשלב ההיתר.', '**זמן** — שנים שבהן הקרקע אינה נזילה.'] },
        { h2: 'מתי זה ריאלי', paras: ['כשהקרקע צמודה לשטח בנוי, נכללת או גובלת בתוכנית מתאר שמסמנת פיתוח, בבעלות מוסדרת (לא מושע מפוזר), וללא מגבלות סטטוטוריות כבדות. [כך אנחנו בודקים היתכנות](/services/real-estate-development/) לפני שממליצים לבעל קרקע להשקיע בתהליך.'] },
      ],
      faq: [
        { q: 'מהם שלבי שינוי ייעוד קרקע?', a: 'בדיקת היתכנות מול תוכניות המתאר, הכנת תוכנית עם יועצים, הגשה ודיון בוועדה המקומית (ולעיתים המחוזית), הפקדה, התנגדויות, אישור ופרסום למתן תוקף, ואז מימוש — היתרים, פרצלציה והיטל השבחה.' },
        { q: 'כמה זמן לוקח שינוי ייעוד מחקלאי למגורים?', a: 'לרוב שנים. תוכנית כזו דורשת בדרך כלל את הוועדה המחוזית, תיאום עם גופים ממשלתיים והתמודדות עם התנגדויות. משך של שנה-שנתיים אפשרי רק בתוכניות פשוטות בסמכות מקומית.' },
        { q: 'מה זה היטל השבחה בשינוי ייעוד?', a: 'תשלום לוועדה המקומית בגובה מחצית מעליית שווי הקרקע שנוצרה בעקבות אישור התוכנית. משולם בעת המימוש — מכירה או קבלת היתר — ולא בעת האישור.' },
      ],
    },
    en: {
      h1: 'Rezoning land — stages, who approves, how long and what it costs',
      metaTitle: 'Land Rezoning in Israel: Process Stages, Committees, Timelines & Betterment Levy | Afik Hanahal',
      description: 'How land rezoning works (e.g. agricultural to residential): who initiates, what happens at the local and district committees, deposit and objections, how long it takes, the betterment levy — and when it is realistic at all.',
      summary: 'Rezoning is the approval of a new zoning plan (TABA) replacing the land\'s current designation — for example agricultural to residential. It passes the local committee and usually the district committee: preparing a plan, hearing, deposit, objections, approval and publication. It usually takes years, triggers a betterment levy on realisation, and only a small share of agricultural land in Israel is actually in such a process.',
      sections: [
        { h2: 'Who can initiate rezoning', paras: ['The landowner (or group of owners), a developer with the owners\' consent, the local authority, or the state (via national and district master plans and the VATMAL). In practice a private plan for a single parcel is rarely approved if it contradicts the master plan — so the first step is checking what higher-level planning says about the area.'] },
        { h2: 'Stages', steps: ['**Feasibility** — do the master plans (national, district, comprehensive municipal) allow the change? If not — odds are very low.', '**Preparing the plan** — architect and urban planning, consultants (traffic, environment, drainage, appraisal), owners\' consent.', '**Submission and hearing** — at the local committee; some plans require the district committee (e.g. rezoning agricultural land).', '**Deposit** — the plan is published for objections.', '**Objections and hearing** — neighbours, green bodies, authorities. The committee decides, sometimes with changes.', '**Approval and publication** — the new designation takes effect.', '**Realisation** — building permits, consolidation and parcellation if needed, and payment of the betterment levy.'] },
        { h2: 'How long it takes', paras: ['Simple plans within local committee authority — sometimes a year or two. A significant rezoning (agricultural to residential) — usually several years, sometimes much more, depending on objections, committee workload and coordination with government bodies. Anyone promising "within a year" should be asked for documents.'] },
        { h2: 'What it costs', bullets: ['**Betterment levy** — the authority collects from the owner half of the value increase created by the plan, on realisation (sale or permit). The big item.', '**Planning costs** — architect, consultants, appraiser, lawyer.', '**Fees and development charges** — at permit stage.', '**Time** — years in which the land is illiquid.'] },
        { h2: 'When it is realistic', paras: ['When the land adjoins a built-up area, falls within or borders a master plan marking development, has orderly ownership (not scattered undivided shares) and no heavy statutory constraints. [This is how we check feasibility](/en/services/real-estate-development/) before advising an owner to invest in the process.'] },
      ],
      faq: [
        { q: 'What are the stages of rezoning land?', a: 'Feasibility against master plans, preparing a plan with consultants, submission and hearing at the local (and sometimes district) committee, deposit, objections, approval and publication, then realisation — permits, parcellation and betterment levy.' },
        { q: 'How long does rezoning from agricultural to residential take?', a: 'Usually years. Such a plan typically requires the district committee, coordination with government bodies and handling objections. One to two years is possible only for simple plans within local authority.' },
        { q: 'What is the betterment levy in rezoning?', a: 'A payment to the local committee equal to half the increase in land value created by the plan\'s approval. Paid on realisation — sale or permit — not on approval.' },
      ],
    },
  },
  {
    slug: 'developer-vs-contractor', cta: 'project', updated: U,
    related: { services: ['real-estate-development', 'project-management-supervision'], areas: ['sharon-region'], guides: ['what-is-real-estate-development', 'construction-supervision'], glossary: ['developer', 'contractor', 'supervisor', 'combination-deal'] },
    he: {
      h1: 'יזם מול קבלן — מה ההבדל ומי אחראי על מה',
      metaTitle: 'מה ההבדל בין יזם לקבלן? אחריות, סיכון ורווח | אפיק הנחל',
      description: 'יזם, קבלן, קבלן מבצע, קבלן משנה ומפקח — מי עושה מה בפרויקט בנייה, מי נושא בסיכון, מי אחראי כלפי הרוכש, ומה זה אומר לבעל קרקע שנכנס לעסקה.',
      summary: 'היזם הוא בעל הפרויקט: הוא רוכש או מארגן את הקרקע, מקדם תכנון ומימון, ומוכר את התוצר — ונושא בסיכון הכולל. הקבלן מבצע את הבנייה עבור היזם לפי חוזה, תמורה ולוח זמנים מוסכמים, ואחראי על איכות הביצוע. מפקח הבנייה מייצג את היזם (או את בעל הקרקע) מול הקבלן. אותה חברה יכולה להיות גם יזם וגם קבלן — אבל התפקידים, האחריות והסיכון נשארים שונים.',
      sections: [
        { h2: 'טבלת השוואה', table: { head: ['', 'יזם', 'קבלן'], rows: [
          ['תפקיד', 'בעל הפרויקט ומנהל הסיכון', 'מבצע הבנייה לפי חוזה'], ['מקור ההכנסה', 'הפער בין העלות לשווי המכירה', 'תמורה חוזית עבור הביצוע'], ['סיכון עיקרי', 'שוק, תכנון, מימון, מכירות', 'עלויות ביצוע, לוחות זמנים, איכות'],
          ['אחריות כלפי הרוכש', 'מוכר הדירה — אחראי לפי חוק המכר (דירות)', 'אחריות ביצוע כלפי היזם; בדק לפי החוזה'], ['רישוי', 'אינו חייב ברישיון קבלן', 'רישום בפנקס הקבלנים לפי היקף וסיווג'], ['מי בוחר את מי', 'היזם בוחר קבלן', 'הקבלן מגיש הצעה / זוכה במכרז'],
        ] } },
        { h2: 'תפקידים נוספים בפרויקט', bullets: ['**קבלן מבצע / קבלן ראשי** — אחראי על כלל הביצוע ומעסיק קבלני משנה.', '**קבלני משנה** — חשמל, אינסטלציה, אלומיניום, גמר.', '**מפקח בנייה** — מייצג את היזם או בעל הקרקע: בודק שהביצוע תואם לתוכניות, למפרט ולתקנים, ומאשר חשבונות. [מה עושה מפקח בנייה](/guides/construction-supervision/).', '**מנהל פרויקט** — מתאם את כל הגורמים: תכנון, רישוי, קבלן, יועצים, לוחות זמנים ותקציב.', '**אדריכל ויועצים** — מתכננים; המהנדס אחראי על הקונסטרוקציה.'] },
        { h2: 'מה זה אומר לבעל קרקע', paras: ['כשבעל קרקע נכנס לעסקת קומבינציה או לשותפות, הוא בעצם נהיה שותף של היזם — לא של הקבלן. השאלות החשובות: מי היזם ומה ניסיונו, איך מובטחת הקרקע (ערבויות, הערת אזהרה), מי מפקח על הביצוע מטעם בעל הקרקע, ומה קורה אם היזם נתקע. [אנחנו מייצגים בעלי קרקע](/services/real-estate-development/) בדיוק בנקודה הזו.'] },
      ],
      faq: [
        { q: 'מה ההבדל בין יזם לקבלן?', a: 'היזם הוא בעל הפרויקט שנושא בסיכון ומרוויח מהמכירה; הקבלן מבצע את הבנייה עבור היזם תמורת תשלום חוזי. היזם אחראי כלפי הרוכשים לפי חוק המכר; הקבלן אחראי כלפי היזם על איכות הביצוע.' },
        { q: 'האם יזם חייב להיות קבלן רשום?', a: 'לא. יזם אינו חייב ברישיון קבלן, אבל הבנייה עצמה חייבת להתבצע על ידי קבלן רשום בפנקס הקבלנים בסיווג המתאים להיקף הפרויקט.' },
        { q: 'מי אחראי על ליקויי בנייה — היזם או הקבלן?', a: 'כלפי רוכש הדירה — היזם/המוכר, לפי חוק המכר (דירות) ותקופות הבדק והאחריות. היזם מצדו יכול לחזור לקבלן לפי החוזה ביניהם.' },
      ],
    },
    en: {
      h1: 'Developer vs. contractor — what is the difference and who is responsible for what',
      metaTitle: 'What Is the Difference Between a Developer and a Contractor? Responsibility, Risk & Profit | Afik Hanahal',
      description: 'Developer, contractor, main contractor, subcontractors and supervisor — who does what in a construction project, who carries the risk, who is liable to the buyer, and what it means for a landowner entering a deal.',
      summary: 'The developer owns the project: acquires or organises the land, promotes planning and financing, and sells the product — carrying the overall risk. The contractor builds for the developer under an agreed contract, price and schedule, and is responsible for construction quality. The construction supervisor represents the developer (or the landowner) opposite the contractor. One company can be both developer and contractor — but the roles, responsibility and risk remain different.',
      sections: [
        { h2: 'Comparison', table: { head: ['', 'Developer', 'Contractor'], rows: [['Role', 'Project owner and risk manager', 'Builds under contract'], ['Income', 'Gap between cost and sale value', 'Contract price for the work'], ['Main risk', 'Market, planning, financing, sales', 'Construction cost, schedule, quality'], ['Liability to the buyer', 'Seller of the apartment — liable under the Sale (Apartments) Law', 'Liable to the developer; defects period per contract'], ['Licensing', 'No contractor licence required', 'Registered in the Contractors Register by scale and class'], ['Who chooses whom', 'The developer chooses a contractor', 'The contractor bids / wins a tender']] } },
        { h2: 'Other roles in a project', bullets: ['**Main contractor** — responsible for all construction, employing subcontractors.', '**Subcontractors** — electrical, plumbing, aluminium, finishes.', '**Construction supervisor** — represents the developer or landowner: checks that construction matches the plans, specification and standards, and approves payments. [What a construction supervisor does](/en/guides/construction-supervision/).', '**Project manager** — coordinates everyone: planning, permits, contractor, consultants, schedule and budget.', '**Architect and consultants** — design; the engineer is responsible for structure.'] },
        { h2: 'What it means for a landowner', paras: ['When a landowner enters a combination deal or partnership, they effectively become the developer\'s partner — not the contractor\'s. The key questions: who is the developer and what is their track record, how is the land secured (guarantees, caveat), who supervises construction on the owner\'s behalf, and what happens if the developer stalls. [We represent landowners](/en/services/real-estate-development/) at exactly this point.'] },
      ],
      faq: [
        { q: 'What is the difference between a developer and a contractor?', a: 'The developer owns the project, carries the risk and profits from sales; the contractor builds for the developer for a contract price. The developer is liable to buyers under the Sale Law; the contractor is liable to the developer for construction quality.' },
        { q: 'Must a developer be a registered contractor?', a: 'No. A developer needs no contractor licence, but the construction itself must be carried out by a contractor registered in the Contractors Register in the class matching the project\'s scale.' },
        { q: 'Who is responsible for construction defects — developer or contractor?', a: 'Toward the apartment buyer — the developer/seller, under the Sale (Apartments) Law and its defect and warranty periods. The developer can in turn claim against the contractor under their contract.' },
      ],
    },
  },
  {
    slug: 'construction-supervision', cta: 'project', updated: U,
    related: { services: ['project-management-supervision', 'real-estate-development'], areas: ['sharon-region'], guides: ['developer-vs-contractor', 'what-is-real-estate-development'], glossary: ['supervisor', 'contractor', 'building-permit', 'developer'] },
    he: {
      h1: 'מה עושה מפקח בנייה ומה כולל פיקוח על פרויקט',
      metaTitle: 'מה עושה מפקח בנייה? תפקידים, בדיקות ולמה צריך פיקוח | אפיק הנחל',
      description: 'מפקח בנייה מייצג את היזם או בעל הנכס מול הקבלן: בודק שהביצוע תואם לתוכניות ולתקנים, מאשר חשבונות, עוקב אחרי לוחות זמנים ותקציב ומתעד. מה כולל פיקוח, מתי צריך אותו וכמה זה חוסך.',
      summary: 'מפקח בנייה אחראי על בקרה מקצועית של עבודות הבנייה מטעם היזם או בעל הנכס: הוא בודק שהביצוע תואם לתוכניות, למפרט, להיתר ולתקנים, מאשר את חשבונות הקבלן לפי ההתקדמות בפועל, עוקב אחרי לוח הזמנים והתקציב, ומתעד ליקויים ודורש את תיקונם. פיקוח טוב הוא ההבדל בין פרויקט שנגמר בזמן ובתקציב לבין שנים של תיקונים ומחלוקות.',
      sections: [
        { h2: 'תפקידי המפקח לאורך הפרויקט', steps: ['**לפני הביצוע** — בדיקת התוכניות, המפרט וכתב הכמויות, סיוע בבחירת קבלן ובניסוח החוזה, ותכנון לוח זמנים.', '**במהלך הביצוע** — ביקורים באתר בתדירות קבועה, בדיקת עבודות לפני כיסוין (יסודות, ברזל, איטום, צנרת), בדיקות מעבדה (בטון), בקרת איכות, ועמידה בהיתר.', '**כספים** — בדיקה ואישור חשבונות הקבלן לפי ביצוע בפועל, בקרת שינויים ותוספות, ומעקב תקציב.', '**לוחות זמנים** — מעקב אחרי אבני דרך, זיהוי עיכובים והתראה מוקדמת.', '**תיעוד** — יומן עבודה, דוחות תקופתיים, צילום, רשימות ליקויים.', '**מסירה** — בדיקות מסירה, פרוטוקול ליקויים, מעקב תיקונים ותקופת בדק.'] },
        { h2: 'מה בודקים באתר בפועל', bullets: ['התאמה למידות ולתוכניות (קווי בניין, מפלסים, פתחים).', 'איכות חומרים מול המפרט — לא "שווה ערך" שלא אושר.', 'עבודות שמכוסות אחר כך: איטום, ברזל, צנרת, בידוד.', 'בטיחות באתר ועמידה בדרישות הרשויות.', 'תיאום בין קבלני המשנה.'] },
        { h2: 'פיקוח מול ניהול פרויקט', paras: ['פיקוח מתמקד בבקרת הביצוע באתר. ניהול פרויקט רחב יותר — הוא מתאם את כל הגורמים מהתכנון והרישוי, דרך המכרזים והחוזים, ועד המסירה, כולל התקציב הכולל ולוח הזמנים. בפרויקטים קטנים אדם אחד ממלא את שני התפקידים; בגדולים מפרידים. [ניהול ופיקוח על פרויקטים](/services/project-management-supervision/) — כך זה עובד אצלנו.'] },
        { h2: 'מתי צריך מפקח', bullets: ['בכל פרויקט בנייה חדש — פיקוח הוא חלק מהשגרה המקצועית.', 'בבניית בית פרטי — כשהבעלים אינו איש מקצוע, המפקח הוא העיניים שלו.', 'בעסקת קומבינציה — מפקח מטעם בעל הקרקע מגן על האינטרס שלו מול היזם והקבלן.', 'בשיפוץ גדול או בתוספת בנייה.'] },
      ],
      faq: [
        { q: 'מה עושה מפקח בנייה?', a: 'מפקח בנייה בודק מטעם היזם או בעל הנכס שהביצוע באתר תואם לתוכניות, למפרט, להיתר ולתקנים; מאשר חשבונות קבלן לפי ביצוע בפועל; עוקב אחרי לוח זמנים ותקציב; ומתעד ליקויים ודורש תיקון.' },
        { q: 'מה ההבדל בין מפקח בנייה למנהל פרויקט?', a: 'המפקח מתמקד בבקרת הביצוע באתר. מנהל הפרויקט מתאם את כל הפרויקט — תכנון, רישוי, מכרזים, חוזים, קבלנים, תקציב ולוח זמנים — מתחילתו ועד מסירתו.' },
        { q: 'האם פיקוח בנייה חובה?', a: 'הדין דורש אחראי לביקורת על הביצוע במסגרת ההיתר (בדרך כלל מהנדס/אדריכל), אבל פיקוח צמוד מטעם המזמין אינו חובה חוקית — הוא החלטה מקצועית שכמעט תמיד מחזירה את עצמה בחיסכון בטעויות, בתוספות ובמחלוקות.' },
      ],
    },
    en: {
      h1: 'What a construction supervisor does and what project supervision includes',
      metaTitle: 'What Does a Construction Supervisor Do? Duties, Inspections & Why It Pays | Afik Hanahal',
      description: 'A construction supervisor represents the developer or owner opposite the contractor: checks that construction matches the plans and standards, approves payments, tracks schedule and budget and documents. What supervision includes, when you need it and what it saves.',
      summary: 'A construction supervisor is responsible for professional control of the works on behalf of the developer or owner: checking that construction matches the plans, specification, permit and standards, approving the contractor\'s invoices by actual progress, tracking schedule and budget, and documenting defects and demanding their correction. Good supervision is the difference between a project finished on time and budget and years of repairs and disputes.',
      sections: [
        { h2: 'The supervisor\'s duties through the project', steps: ['**Before construction** — reviewing plans, specification and bill of quantities, helping select a contractor and draft the contract, and scheduling.', '**During construction** — regular site visits, inspecting works before they are covered (foundations, rebar, waterproofing, piping), lab tests (concrete), quality control and permit compliance.', '**Money** — checking and approving contractor invoices by actual progress, controlling changes and extras, tracking the budget.', '**Schedule** — tracking milestones, spotting delays, early warning.', '**Documentation** — site diary, periodic reports, photos, defect lists.', '**Handover** — handover inspections, defect protocol, repair tracking and the defects period.'] },
        { h2: 'What is actually inspected on site', bullets: ['Match to dimensions and plans (setbacks, levels, openings).', 'Material quality against the specification — no unapproved "equivalents".', 'Works covered later: waterproofing, rebar, piping, insulation.', 'Site safety and compliance with authorities.', 'Coordination between subcontractors.'] },
        { h2: 'Supervision vs. project management', paras: ['Supervision focuses on controlling construction on site. Project management is broader — coordinating everything from design and permits, through tenders and contracts, to handover, including the overall budget and schedule. In small projects one person does both; in large ones they are separated. [Project management and supervision](/en/services/project-management-supervision/) — how it works with us.'] },
        { h2: 'When you need a supervisor', bullets: ['In every new construction project — supervision is professional routine.', 'Building a private house — when the owner is not a professional, the supervisor is their eyes.', 'In a combination deal — a supervisor on the landowner\'s behalf protects their interest opposite the developer and contractor.', 'In a major renovation or addition.'] },
      ],
      faq: [
        { q: 'What does a construction supervisor do?', a: 'On behalf of the developer or owner, checks that on-site construction matches the plans, specification, permit and standards; approves contractor invoices by actual progress; tracks schedule and budget; and documents defects and demands correction.' },
        { q: 'What is the difference between a supervisor and a project manager?', a: 'The supervisor focuses on controlling construction on site. The project manager coordinates the whole project — design, permits, tenders, contracts, contractors, budget and schedule — from start to handover.' },
        { q: 'Is construction supervision mandatory?', a: 'The law requires a party responsible for inspecting execution under the permit (usually an engineer/architect), but close supervision on the client\'s behalf is not a legal duty — it is a professional decision that almost always pays for itself in fewer mistakes, extras and disputes.' },
      ],
    },
  },
  {
    slug: 'how-to-sell-property', cta: 'sell', updated: U,
    related: { services: ['sell-your-property', 'rent-your-property'], areas: ['hod-hasharon', 'kfar-saba', 'raanana', 'herzliya'], guides: ['property-valuation'], glossary: ['capital-gains-tax', 'exclusivity', 'memorandum-of-understanding', 'caveat', 'appraiser'] },
    he: {
      h1: 'איך מוכרים נכס — המדריך המלא למכירת דירה או בית',
      metaTitle: 'איך מוכרים דירה או בית? שלבים, הכנה, תמחור ומיסוי | אפיק הנחל',
      description: 'מדריך מעשי למכירת נכס בישראל: מה בודקים לפני הפרסום, איך מתמחרים נכון, איך מכינים את הנכס, איך משווקים, מה קורה במשא ומתן, מה זה זיכרון דברים, ומה עם מס שבח.',
      summary: 'מכירת נכס מוצלחת עוברת שישה שלבים: **בדיקה** (רישום, היתר, מיסוי), **תמחור** לפי עסקאות אמיתיות, **הכנה** של הנכס והחומרים, **שיווק** ממוקד וסינון רוכשים, **משא ומתן** וזיכרון דברים, ו**חוזה** עם עורך דין עד העברת הזכויות. הטעות הנפוצה ביותר היא תמחור גבוה מדי — נכס ש"עומד" נמכר בסוף בפחות.',
      sections: [
        { h2: 'שלב 1 — בדיקות לפני הפרסום', bullets: ['**רישום** — נסח טאבו או אישור זכויות; הערות אזהרה, משכנתא (ומה נדרש לסילוקה).', '**היתר** — האם המצב בפועל תואם להיתר? תוספות ללא היתר מורידות מחיר ומסבכות חוזה.', '**מיסוי** — האם יש פטור ממס שבח (דירה יחידה בתנאים) או חבות? זה משפיע על הנטו ועל המחיר שאפשר לקבל.', '**ועד בית ותשלומים** — חובות, שיפוצים מתוכננים, תמ"א 38 בדרך?'] },
        { h2: 'שלב 2 — תמחור', paras: ['המחיר נקבע לפי עסקאות שנסגרו בפועל בבניין ובשכונה (לא לפי מחירי מודעות), בהתאמה למצב הנכס, לקומה, לכיוון, לחניה ולמרפסת. מחיר "לניסיון" גבוה מדי גורם לנכס לעמוד, ורוכשים לומדים להתעלם ממנו. [איך יודעים כמה הנכס שווה](/guides/property-valuation/).'] },
        { h2: 'שלב 3 — הכנה', bullets: ['תיקונים קטנים, צביעה, ניקיון, סידור — כמעט תמיד משתלמים.', 'שיפוץ גדול לפני מכירה — לרוב לא מחזיר את עצמו.', 'צילום מקצועי באור טוב; תשריט; רשימת יתרונות.', 'מסמכים מוכנים מראש חוסכים שבועות.'] },
        { h2: 'שלב 4 — שיווק וסינון', paras: ['פרסום בערוצים הנכונים, פנייה למאגר רוכשים, וסינון: להראות את הנכס לרוכשים רלוונטיים ובעלי יכולת, לא לכל מי שמתקשר. משוב מהסיורים הוא המידע הכי חשוב על המחיר.'] },
        { h2: 'שלב 5 — משא ומתן וזיכרון דברים', paras: ['מנהלים משא ומתן על מחיר, מועד פינוי ותנאי תשלום. זיכרון דברים הוא מסמך מחייב — לא לחתום בלי עורך דין. עדיף לעבור ישר להסכם מכר.'] },
        { h2: 'שלב 6 — חוזה והעברת זכויות', paras: ['הסכם מכר עם עורך דין, דיווח לרשות המסים, אישורי מסים, סילוק משכנתא אם יש, ורישום הרוכש. הליווי לא נגמר בחתימה. [כך אנחנו מלווים מכירה](/services/sell-your-property/).'] },
      ],
      faq: [
        { q: 'איך משווקים דירה למכירה?', a: 'בודקים רישום, היתר ומיסוי; מתמחרים לפי עסקאות אמיתיות; מכינים את הנכס ומצלמים מקצועית; מפרסמים בערוצים הנכונים ופונים למאגר רוכשים; מסננים ומציגים לרוכשים רלוונטיים; ומנהלים משא ומתן עד הסכם מכר עם עורך דין.' },
        { q: 'מה צריך לבדוק לפני שמוכרים נכס?', a: 'נסח טאבו והערות, התאמה להיתר, חבות או פטור ממס שבח, משכנתא ותנאי סילוקה, ומצב ועד הבית. בדיקות אלה מונעות הפתעות במשא ומתן ובחוזה.' },
        { q: 'כמה זמן לוקח למכור דירה?', a: 'נכס מתומחר נכון בשרון נמכר לרוב תוך שבועות עד חודשים ספורים. ההשפעה הגדולה ביותר על משך המכירה היא המחיר ההתחלתי.' },
        { q: 'האם צריך מתווך כדי למכור דירה?', a: 'לא חובה, אבל מתווך מקצועי מביא תמחור מבוסס נתונים, מאגר רוכשים, סינון, ניהול משא ומתן וניסיון בחוזים — ובדרך כלל מגיע למחיר טוב יותר ובזמן קצר יותר. חשוב לחתום הסכם תיווך בכתב.' },
      ],
    },
    en: {
      h1: 'How to sell a property — the complete guide to selling an apartment or house',
      metaTitle: 'How to Sell an Apartment or House? Stages, Preparation, Pricing & Tax | Afik Hanahal',
      description: 'A practical guide to selling property in Israel: what to check before listing, how to price correctly, how to prepare the property, how to market, negotiation, the memorandum of understanding, and capital gains tax.',
      summary: 'A successful sale passes six stages: **checks** (registration, permit, tax), **pricing** by real deals, **preparing** the property and materials, targeted **marketing** and buyer screening, **negotiation** and memorandum, and the **contract** with a lawyer through transfer of title. The most common mistake is overpricing — a property that "sits" ends up selling for less.',
      sections: [
        { h2: 'Stage 1 — checks before listing', bullets: ['**Registration** — Tabu extract or rights confirmation; caveats, mortgage (and what its discharge requires).', '**Permit** — does the actual state match the permit? Unpermitted additions lower the price and complicate the contract.', '**Tax** — is there a capital gains exemption (single home, under conditions) or a liability? It affects the net and the price you can accept.', '**Building committee and payments** — debts, planned works, TAMA 38 coming?'] },
        { h2: 'Stage 2 — pricing', paras: ['Price by deals actually closed in the building and neighbourhood (not listing prices), adjusted for condition, floor, orientation, parking and balcony. A "trial" price set too high makes the property sit, and buyers learn to ignore it. [How to know what your property is worth](/en/guides/property-valuation/).'] },
        { h2: 'Stage 3 — preparation', bullets: ['Small repairs, paint, cleaning, staging — almost always pay off.', 'A major renovation before selling — usually does not.', 'Professional photos in good light; floor plan; list of advantages.', 'Documents ready in advance save weeks.'] },
        { h2: 'Stage 4 — marketing and screening', paras: ['Advertising in the right channels, outreach to a buyer base, and screening: showing the property to relevant, capable buyers, not everyone who calls. Feedback from showings is the most important information about the price.'] },
        { h2: 'Stage 5 — negotiation and memorandum', paras: ['Negotiate price, vacancy date and payment terms. A memorandum of understanding is binding — do not sign without a lawyer. Better to go straight to a sale agreement.'] },
        { h2: 'Stage 6 — contract and transfer', paras: ['Sale agreement with a lawyer, reporting to the Tax Authority, tax confirmations, mortgage discharge if any, and registering the buyer. Support does not end at signing. [How we accompany a sale](/en/services/sell-your-property/).'] },
      ],
      faq: [
        { q: 'How do you market an apartment for sale?', a: 'Check registration, permit and tax; price by real deals; prepare the property and photograph it professionally; advertise in the right channels and reach a buyer base; screen and show to relevant buyers; and negotiate to a sale agreement with a lawyer.' },
        { q: 'What should I check before selling a property?', a: 'Tabu extract and notes, permit compliance, capital gains liability or exemption, mortgage and discharge terms, and the building committee\'s status. These checks prevent surprises in negotiation and contract.' },
        { q: 'How long does it take to sell an apartment?', a: 'A correctly priced property in the Sharon usually sells within weeks to a few months. The biggest influence on time to sell is the initial price.' },
        { q: 'Do I need a broker to sell an apartment?', a: 'Not mandatory, but a professional broker brings data-based pricing, a buyer base, screening, negotiation and contract experience — and usually reaches a better price in less time. Sign a written brokerage agreement.' },
      ],
    },
  },
  {
    slug: 'property-valuation', cta: 'sell', updated: U,
    related: { services: ['sell-your-property', 'land-brokerage'], areas: ['hod-hasharon', 'raanana'], guides: ['how-to-sell-property', 'land-due-diligence-checklist'], glossary: ['appraiser', 'building-rights', 'yield', 'capital-gains-tax'] },
    he: {
      h1: 'איך יודעים כמה הנכס שלי שווה — שיטות הערכת שווי',
      metaTitle: 'כמה הנכס שלי שווה? איך מעריכים שווי דירה, בית או קרקע | אפיק הנחל',
      description: 'איך מעריכים שווי נכס: שיטת ההשוואה לעסקאות דומות, מה מעלה ומה מוריד מחיר, איפה בודקים עסקאות אמיתיות, מתי צריך שמאי, ולמה קרקע מוערכת אחרת לגמרי מדירה.',
      summary: 'שווי נכס למגורים נקבע בעיקר בשיטת ההשוואה: עסקאות שנסגרו בפועל בנכסים דומים בסביבה, בהתאמה למאפייני הנכס — שטח, קומה, מצב, חניה, מרפסת, כיוון ותוספות. קרקע מוערכת אחרת: לפי הייעוד, זכויות הבנייה והתכנון העתידי. הערכה מסודרת משווה לעסקאות ולא למודעות, ובעסקאות משמעותיות נעזרים בשמאי מקרקעין.',
      sections: [
        { h2: 'שלוש שיטות הערכה', bullets: ['**השוואה** — לעסקאות דומות שנסגרו (הגישה המרכזית לדירות ובתים).', '**היוון הכנסות** — לנכסים מניבים: שכר הדירה השנתי חלקי שיעור התשואה המקובל.', '**עלות / שווי שיורי** — לקרקע ולפרויקטים: שווי התוצר המוגמר פחות כל העלויות והרווח היזמי.'] },
        { h2: 'מה מעלה ומה מוריד מחיר בדירה', table: { head: ['מעלה', 'מוריד'], rows: [['קומה גבוהה עם מעלית, נוף', 'קומת קרקע ללא גינה, קומה גבוהה ללא מעלית'], ['חניה בטאבו, מחסן, מרפסת שמש', 'ללא חניה, מרפסת סגורה ללא היתר'], ['בניין חדש או משופץ, תמ"א מאושרת', 'בניין ותיק ללא תוכנית, ועד בית עם חובות'], ['תכנון טוב וכיווני אוויר', 'תוספות ללא היתר, חריגות'], ['קרבה לפארק, חינוך, רכבת', 'כביש ראשי, רעש']] } },
        { h2: 'איפה בודקים עסקאות אמיתיות', paras: ['מאגר עסקאות הנדל"ן של רשות המסים מציג את מחירי העסקאות שדווחו בפועל, לפי כתובת ותקופה. זה המקור, ולא מחירי המודעות בפורטלים, שמשקפים ציפיות ולא תוצאות. חשוב להשוות לעסקאות מהחודשים האחרונים ולנכסים דומים באמת.'] },
        { h2: 'למה קרקע היא סיפור אחר', paras: ['בקרקע אין "שטח דירה" להשוות אליו. הערך נקבע לפי מה מותר לבנות (תב"ע, זכויות), מה צפוי (תוכניות מתאר), מבנה הבעלות, ומיסוי והיטלים בדרך למימוש. שתי חלקות סמוכות יכולות להיות שוות פי עשרה זו מזו. [מה בודקים לפני רכישת קרקע](/guides/land-due-diligence-checklist/).'] },
        { h2: 'מתי צריך שמאי מקרקעין', bullets: ['עסקאות גדולות או מורכבות, ובעיקר קרקע.', 'מחלוקת בין יורשים או שותפים.', 'משכנתא (הבנק דורש שמאות).', 'היטל השבחה, מס שבח והליכים משפטיים.'] },
      ],
      faq: [
        { q: 'איך יודעים כמה הבית שלי שווה?', a: 'משווים לעסקאות שנסגרו בפועל בבתים דומים בשכונה (מאגר רשות המסים), ומתאימים לפי שטח הבית והמגרש, מצב, זכויות בנייה נותרות, היתרים ותוספות. בבתים פרטיים זכויות הבנייה הנותרות הן מרכיב מרכזי בשווי.' },
        { q: 'האם הערכת שווי של מתווך שווה לשמאות?', a: 'לא. מתווך נותן הערכת שוק לצורך תמחור ושיווק; שמאי מקרקעין מוסמך נותן חוות דעת מקצועית מחייבת לצרכים משפטיים, מימון ומיסוי. לרוב המכירות הערכת שוק מספיקה; לעסקאות מורכבות — שמאי.' },
        { q: 'מה ההבדל בין מחיר מבוקש למחיר עסקה?', a: 'מחיר מבוקש הוא הציפייה של המוכר במודעה; מחיר עסקה הוא מה ששולם בפועל ודווח לרשות המסים. הפער ביניהם יכול להיות משמעותי, ולכן מתמחרים לפי עסקאות.' },
      ],
    },
    en: {
      h1: 'How to know what your property is worth — valuation methods',
      metaTitle: 'What Is My Property Worth? Valuing an Apartment, House or Land | Afik Hanahal',
      description: 'How property value is assessed: the comparison method, what raises and lowers price, where to check real deals, when you need an appraiser, and why land is valued completely differently from an apartment.',
      summary: 'Residential value is set mainly by comparison: deals actually closed on similar properties nearby, adjusted for the property\'s features — size, floor, condition, parking, balcony, orientation and additions. Land is valued differently: by designation, building rights and future planning. A proper valuation compares to deals, not listings, and significant transactions use a licensed appraiser.',
      sections: [
        { h2: 'Three valuation methods', bullets: ['**Comparison** — to similar closed deals (the main approach for apartments and houses).', '**Income capitalisation** — for income property: annual rent divided by the customary yield.', '**Cost / residual value** — for land and projects: finished value minus all costs and developer\'s profit.'] },
        { h2: 'What raises and lowers an apartment\'s price', table: { head: ['Raises', 'Lowers'], rows: [['High floor with lift, view', 'Ground floor without garden, high floor without lift'], ['Registered parking, storage, sun balcony', 'No parking, enclosed balcony without permit'], ['New or renovated building, approved TAMA', 'Old building without a plan, committee debts'], ['Good layout and orientation', 'Unpermitted additions, deviations'], ['Near park, schools, railway', 'Main road, noise']] } },
        { h2: 'Where to check real deals', paras: ['The Tax Authority\'s real estate transactions database shows actually reported deal prices by address and period. That is the source — not portal listing prices, which reflect expectations, not results. Compare to deals from recent months and truly similar properties.'] },
        { h2: 'Why land is a different story', paras: ['Land has no "apartment area" to compare. Value follows what may be built (zoning plan, rights), what is expected (master plans), ownership structure, and taxes and levies on the way to realisation. Two adjacent parcels can differ tenfold. [What to check before buying land](/en/guides/land-due-diligence-checklist/).'] },
        { h2: 'When you need a licensed appraiser', bullets: ['Large or complex deals, especially land.', 'Disputes between heirs or partners.', 'Mortgage (the bank requires an appraisal).', 'Betterment levy, capital gains and legal proceedings.'] },
      ],
      faq: [
        { q: 'How do I know what my house is worth?', a: 'Compare to deals actually closed on similar houses in the neighbourhood (Tax Authority database), adjusting for house and plot size, condition, remaining building rights, permits and additions. For houses, remaining building rights are a central value component.' },
        { q: 'Is a broker\'s valuation the same as an appraisal?', a: 'No. A broker gives a market estimate for pricing and marketing; a licensed appraiser gives a binding professional opinion for legal, financing and tax purposes. For most sales a market estimate is enough; for complex deals — an appraiser.' },
        { q: 'What is the difference between asking price and deal price?', a: 'The asking price is the seller\'s expectation in the listing; the deal price is what was actually paid and reported to the Tax Authority. The gap can be significant, which is why pricing follows deals.' },
      ],
    },
  },
  {
    slug: 'agricultural-land-investment', cta: 'buy', updated: U,
    related: { services: ['land-investment', 'land-brokerage'], areas: ['sharon-region'], guides: ['land-due-diligence-checklist', 'rezoning-process'], glossary: ['agricultural-land', 'land-thawing', 'rezoning', 'private-land', 'district-committee', 'betterment-levy'] },
    he: {
      h1: 'השקעה בקרקע חקלאית — מה חשוב לדעת לפני שקונים',
      metaTitle: 'השקעה בקרקע חקלאית: סיכונים, סימנים טובים ומה בודקים | אפיק הנחל',
      description: 'האם קרקע חקלאית היא השקעה טובה? מה ההבדל בין קרקע חקלאית "בתהליך" לקרקע שתישאר חקלאית, אילו סימנים מעידים על פוטנציאל אמיתי, מהם הסיכונים, ואיך מונעים טעות יקרה.',
      summary: 'קרקע חקלאית היא קרקע שייעודה לפי התב"ע חקלאי, ואי אפשר לבנות עליה מגורים ללא שינוי ייעוד. היא יכולה להיות השקעה טובה **רק** כשהיא צמודה לשטח בנוי מבוקש, כשתוכניות המתאר מסמנות בה פיתוח, כשהבעלות מוסדרת, וכשאופק ההשקעה ארוך. רוב הקרקעות החקלאיות בישראל אינן בתהליך שינוי ייעוד, ומחיר נמוך אינו סימן להזדמנות אלא לסיכון.',
      sections: [
        { h2: 'שני סוגים של קרקע חקלאית', table: { head: ['קרקע "עם תוכנית"', 'קרקע "עם סיפור"'], rows: [['נכללת בתוכנית מתאר או בתוכנית בהכנה שמייעדת אותה לפיתוח', 'הבטחה בעל-פה ש"היא תופשר"'], ['צמודה לשטח בנוי ולתשתיות', 'רחוקה מהעיר, ליד שטחים פתוחים או תשתיות לאומיות'], ['בעלות מוסדרת, חלקה מוגדרת', 'מושע עם עשרות שותפים'], ['מחיר שמשקף סיכוי ריאלי', 'מחיר נמוך "כי זה עוד יעלה"']] } },
        { h2: 'סימנים לפוטנציאל אמיתי', bullets: ['תוכנית מתאר (מחוזית / כוללנית עירונית) שמסמנת את האזור לפיתוח עתידי.', 'תוכנית בהכנה או בהפקדה שמשנה את הייעוד — עם מספר תוכנית שאפשר לבדוק.', 'גבול ישיר עם השטח הבנוי, כבישים ותשתיות.', 'רשות מקומית שדוחפת להרחבה.', 'חלקה נפרדת בטאבו או הסכם שיתוף מסודר.'] },
        { h2: 'הסיכונים', bullets: ['**זמן** — גם קרקע "בתהליך" יכולה לחכות שנים רבות.', '**אי-ודאות תכנונית** — תוכניות משתנות, מתבטלות ומצטמצמות.', '**מיסוי והיטלים** — היטל השבחה במימוש, מס שבח במכירה, ולעיתים הפקעות לצרכי ציבור שמקטינות את החלקה.', '**נזילות** — קשה למכור מהר, במיוחד במושע.', '**מכירה בשיטת ה"פרויקט"** — שיווק המוני של חלקים קטנים בקרקע חקלאית רחוקה, במחירים שלא משקפים את השווי. זה הדפוס שבו רוב הכסף אובד.'] },
        { h2: 'מה בודקים לפני שקונים', paras: ['בדיוק את [12 הבדיקות](/guides/land-due-diligence-checklist/): נסח ובעלות, תב"ע וייעוד, תוכניות מתאר, מגבלות, גישה, מיסוי והשוואה לעסקאות. ובנוסף: לבקש לראות את מספר התוכנית שמבטיחים לכם — ולבדוק אותה במערכות התכנון. [כך אנחנו מלווים משקיעים](/services/land-investment/).'] },
      ],
      faq: [
        { q: 'האם קרקע חקלאית היא השקעה טובה?', a: 'רק בתנאים ברורים: צמידות לשטח בנוי מבוקש, תוכנית מתאר או תוכנית בהכנה שמסמנת פיתוח, בעלות מוסדרת ואופק השקעה ארוך. בלי אלה, מדובר בהימור עם נזילות נמוכה.' },
        { q: 'מתי כדאי להשקיע בקרקע חקלאית?', a: 'כשהקרקע צמודה לאזור בנוי עם לחץ ביקוש, כשיש תוכניות תכנוניות ממשיות לאזור, כשאפשר לאמת אותן במסמכים, וכשאתם מוכנים להמתין שנים. תמיד אחרי בדיקת נאותות מלאה.' },
        { q: 'מה זה "הפשרת קרקע"?', a: 'ביטוי עממי לשינוי ייעוד של קרקע חקלאית לייעוד בנייה. זהו הליך תכנוני סטטוטורי ארוך, ולא אירוע שקורה "מעצמו" עם הזמן.' },
      ],
    },
    en: {
      h1: 'Investing in agricultural land — what to know before buying',
      metaTitle: 'Agricultural Land Investment: Risks, Good Signs and What to Check | Afik Hanahal',
      description: 'Is agricultural land a good investment? The difference between land "in process" and land that will stay agricultural, the signs of real potential, the risks, and how to avoid an expensive mistake.',
      summary: 'Agricultural land is land designated agricultural under the zoning plan; housing cannot be built on it without rezoning. It can be a good investment **only** when it adjoins a sought-after built-up area, when master plans mark it for development, when ownership is orderly and when the horizon is long. Most agricultural land in Israel is not in a rezoning process, and a low price is not a sign of opportunity but of risk.',
      sections: [
        { h2: 'Two kinds of agricultural land', table: { head: ['Land "with a plan"', 'Land "with a story"'], rows: [['Within a master plan or a plan in preparation designating it for development', 'A verbal promise that it "will be thawed"'], ['Adjoining the built-up area and infrastructure', 'Far from the city, next to open spaces or national infrastructure'], ['Orderly ownership, defined parcel', 'Undivided shares with dozens of partners'], ['A price reflecting a realistic chance', 'A low price "because it will go up"']] } },
        { h2: 'Signs of real potential', bullets: ['A master plan (district / comprehensive municipal) marking the area for future development.', 'A plan in preparation or deposited that changes the designation — with a plan number you can check.', 'A direct border with the built-up area, roads and infrastructure.', 'A local authority pushing for expansion.', 'A separate parcel in Tabu or an orderly sharing agreement.'] },
        { h2: 'The risks', bullets: ['**Time** — even land "in process" can wait many years.', '**Planning uncertainty** — plans change, are cancelled or shrink.', '**Taxes and levies** — betterment levy on realisation, capital gains on sale, and sometimes expropriation for public needs.', '**Liquidity** — hard to sell quickly, especially undivided shares.', '**The "project" sales method** — mass marketing of small shares in distant agricultural land at prices that do not reflect value. This is where most money is lost.'] },
        { h2: 'What to check before buying', paras: ['Exactly the [12 checks](/en/guides/land-due-diligence-checklist/): extract and ownership, zoning plan and designation, master plans, constraints, access, taxation and comparable deals. Plus: ask to see the plan number you are promised — and check it in the planning systems. [How we support investors](/en/services/land-investment/).'] },
      ],
      faq: [
        { q: 'Is agricultural land a good investment?', a: 'Only under clear conditions: adjoining a sought-after built-up area, a master plan or plan in preparation marking development, orderly ownership and a long horizon. Without these it is a gamble with low liquidity.' },
        { q: 'When is it worth investing in agricultural land?', a: 'When the land adjoins a built-up area with demand pressure, when there are real planning schemes for the area that can be verified in documents, and when you are ready to wait years. Always after full due diligence.' },
        { q: 'What is "land thawing"?', a: 'A colloquial term for rezoning agricultural land to a building designation. It is a long statutory planning process, not something that happens "by itself" over time.' },
      ],
    },
  },
]
