// Money pages. Each answers: what we do, who it is for, how we work, what you get, where, why us, next step.
const U = '2026-09-16'
export const SERVICES = [
  {
    slug: 'land-brokerage', cta: 'land', updated: U,
    related: { services: ['land-investment', 'real-estate-development'], areas: ['sharon-region', 'hod-hasharon', 'kfar-saba'], guides: ['land-due-diligence-checklist', 'rezoning-process', 'agricultural-land-investment'], glossary: ['taba', 'building-rights', 'tabu', 'private-land', 'betterment-levy'] },
    he: {
      h1: 'שיווק ותיווך קרקעות ומגרשים בשרון ובמרכז', cardTitle: 'שיווק ותיווך קרקעות', serviceType: 'תיווך קרקעות',
      metaTitle: 'תיווך ושיווק קרקעות ומגרשים בשרון | אפיק הנחל',
      description: 'שיווק ותיווך קרקעות פרטיות ומגרשים בשרון ובמרכז: איתור, בדיקת זכויות ותב"ע, ייעוץ מיסוי, משא ומתן וליווי עד רישום בטאבו. גם נכסים בלעדיים שאינם בפורטלים.',
      summary: 'אפיק הנחל מאתרת, משווקת ומתווכת קרקעות פרטיות ומגרשים בשרון ובמרכז, ומלווה את העסקה מהבדיקה הראשונה ועד לרישום בטאבו. חלק מהקרקעות שאנחנו משווקים אינן מפורסמות בפורטלים הפתוחים. השירות מתאים לבעלי קרקע שרוצים למכור, לרוכשים ולמשקיעים שמחפשים קרקע עם פוטנציאל.',
      sections: [
        { h2: 'מה כולל השירות', bullets: [
          '**איתור קרקעות ומגרשים** — מיפוי שיטתי של השוק והגעה לקרקעות לפני שהן עולות לשוק הפתוח.',
          '**בדיקת זכויות ותב"ע** — ייעוד הקרקע, זכויות הבנייה, מגבלות ואפשרויות שינוי ייעוד, לפני שמדברים על מחיר.',
          '**ייעוץ מיסוי והערכת שווי** — חישוב מס שבח, מס רכישה והיטל השבחה, והערכת שווי עצמאית.',
          '**ניהול משא ומתן** — מול רוכשים פרטיים, קבוצות רכישה וחברות בנייה.',
          '**ליווי חוזי ומשפטי** — עבודה צמודה עם עורכי דין למקרקעין, מזיכרון דברים ועד החוזה.',
          '**רישום בטאבו** — ליווי עד להשלמת הרישום, כי רק אז העסקה באמת הושלמה.',
        ] },
        { h2: 'למי זה מתאים', bullets: [
          '**בעלי קרקע** — יורשים, חקלאים ומשפחות שמחזיקות מגרש או שדה ורוצים להבין מה הוא שווה ומה אפשר לעשות איתו.',
          '**רוכשים פרטיים** — שמחפשים מגרש לבניית בית או קרקע לטווח ארוך.',
          '**משקיעים** — שמחפשים קרקע בשלבי תכנון עם פוטנציאל השבחה.',
          '**יזמים וחברות בנייה** — שצריכים קרקע מתאימה לפרויקט הבא.',
        ] },
        { h2: 'איך זה עובד', steps: [
          'שיחת היכרות קצרה — מה יש לכם או מה אתם מחפשים.',
          'בדיקה ראשונית של הקרקע: נסח טאבו, תב"ע, ייעוד וזכויות.',
          'הערכת שווי ותמונת מיסוי צפויה.',
          'שיווק ממוקד (למוכרים) או הצגת קרקעות מתאימות (לרוכשים).',
          'ניהול משא ומתן, ליווי משפטי וחתימה.',
          'ליווי עד לרישום בטאבו.',
        ] },
        { h2: 'איפה', paras: ['הליבה: השרון — הוד השרון, כפר סבא, רעננה, הרצליה, רמת השרון ונתניה — והמרכז. אנחנו פעילים גם בצפון ובדרום כאשר יש קרקע עם פוטנציאל אמיתי.'] },
        { h2: 'למה אפיק הנחל', paras: ['כ-30 שנות ניסיון בקרקעות, רשת קשרים ארוכת שנים עם בעלי קרקע, עורכי דין, שמאים וחברות בנייה, ושקיפות מלאה בכל שלב. אנחנו מציגים ללקוח את התמונה המלאה — כולל המיסוי והסיכונים — לפני שהוא מחליט.'] },
      ],
      faq: [
        { q: 'מה ההבדל בין תיווך קרקע לתיווך דירה?', a: 'בעסקת קרקע רוב הערך נקבע על ידי התכנון: ייעוד, זכויות בנייה, תב"ע וסיכויי שינוי ייעוד. לכן תיווך קרקע דורש בדיקה תכנונית ומיסויית מעמיקה הרבה יותר מעסקת דירה, שבה הנכס והשימוש בו כבר ברורים.' },
        { q: 'כמה זמן לוקח למכור קרקע?', a: 'תלוי בייעוד ובמצב התכנוני. מגרש לבנייה עם זכויות ברורות יכול להימכר תוך שבועות; קרקע חקלאית או קרקע בתהליך תכנון דורשת יותר זמן, כי הרוכשים בודקים לעומק. הכנה נכונה של מסמכים ובדיקות מראש מקצרת את התהליך.' },
        { q: 'האם אתם עובדים בבלעדיות?', a: 'בלעדיות מאפשרת לנו להשקיע בשיווק ממוקד ולהגן על המחיר, אבל היא לא חובה. נשמח להסביר בפגישה מה מתאים לנכס שלכם.' },
        { q: 'מה צריך להכין לפני שפונים אליכם עם קרקע?', a: 'נסח טאבו עדכני (או אישור זכויות), גוש וחלקה, וכל מסמך תכנוני שיש בידכם. את השאר — תב"ע, זכויות והערכת שווי — אנחנו בודקים.' },
      ],
    },
    en: {
      h1: 'Land & plot marketing and brokerage in the Sharon and Central Israel', cardTitle: 'Land marketing & brokerage', serviceType: 'Land brokerage',
      metaTitle: 'Land & Plot Brokerage in the Sharon Region | Afik Hanahal',
      description: 'Marketing and brokerage of private land and plots in the Sharon and Central Israel: sourcing, rights and zoning checks, tax advice, negotiation and support through Tabu registration. Including exclusive off-portal listings.',
      summary: 'Afik Hanahal sources, markets and brokers private land and plots in the Sharon and Central Israel, accompanying the deal from the first check to Tabu registration. Some of the land we market never appears on public portals. The service suits landowners who want to sell, and buyers and investors looking for land with potential.',
      sections: [
        { h2: 'What the service includes', bullets: [
          '**Sourcing land and plots** — systematic market mapping, reaching plots before they hit the open market.',
          '**Rights and zoning check** — designation, building rights, restrictions and rezoning options, before any price talk.',
          '**Tax advice and valuation** — capital gains tax, purchase tax and betterment levy, plus an independent valuation.',
          '**Negotiation** — opposite private buyers, purchase groups and construction companies.',
          '**Legal and contractual support** — with real estate lawyers, from memorandum to contract.',
          '**Tabu registration** — we stay until registration is complete.',
        ] },
        { h2: 'Who it is for', bullets: ['**Landowners** — heirs, farmers and families holding a plot or field.', '**Private buyers** — looking for a plot to build on or land to hold long term.', '**Investors** — seeking land at planning stages with improvement potential.', '**Developers and builders** — needing the right land for the next project.'] },
        { h2: 'How it works', steps: ['A short intro call — what you own or what you are looking for.', 'Initial land check: Tabu extract, zoning plan, designation and rights.', 'Valuation and expected tax picture.', 'Targeted marketing (sellers) or matching plots (buyers).', 'Negotiation, legal support and signing.', 'Support through Tabu registration.'] },
        { h2: 'Where', paras: ['Core: the Sharon — Hod Hasharon, Kfar Saba, Ra\'anana, Herzliya, Ramat Hasharon and Netanya — and Central Israel. We also work in the north and south when the land has real potential.'] },
        { h2: 'Why Afik Hanahal', paras: ['About 30 years in land, a long-standing network of landowners, lawyers, appraisers and builders, and full transparency at every step — including taxation and risks — before you decide.'] },
      ],
      faq: [
        { q: 'How is land brokerage different from apartment brokerage?', a: 'In a land deal most of the value is set by planning: designation, building rights, the zoning plan and rezoning prospects. Land brokerage therefore requires far deeper planning and tax due diligence than an apartment, where the asset and its use are already clear.' },
        { q: 'How long does it take to sell land?', a: 'It depends on designation and planning status. A building plot with clear rights can sell within weeks; agricultural land or land in planning takes longer because buyers check in depth. Preparing documents and checks in advance shortens the process.' },
        { q: 'Do you work on an exclusive basis?', a: 'Exclusivity lets us invest in focused marketing and protect the price, but it is not mandatory. We will explain in a meeting what suits your property.' },
        { q: 'What should I prepare before contacting you about land?', a: 'A current Tabu extract (or rights confirmation), block and parcel numbers, and any planning document you have. The rest — zoning, rights and valuation — we check.' },
      ],
    },
  },
  {
    slug: 'real-estate-development', cta: 'project', updated: U,
    related: { services: ['land-brokerage', 'project-marketing'], areas: ['hod-hasharon', 'sharon-region'], guides: ['what-is-real-estate-development', 'rezoning-process', 'developer-vs-contractor', 'construction-supervision'], glossary: ['developer', 'taba', 'rezoning', 'building-permit', 'combination-deal', 'local-committee'] },
    he: {
      h1: 'יזמות נדל"ן וקידום תוכניות — מהקרקע ועד העלייה לקרקע', cardTitle: 'יזמות נדל"ן וקידום תוכניות', serviceType: 'יזמות נדל"ן',
      metaTitle: 'יזמות נדל"ן בשרון: קידום תוכניות, שינוי ייעוד והשבחת קרקע | אפיק הנחל',
      description: 'ייזום פרויקטים חדשים וקידום תוכניות נדל"ן: שינויי ייעוד, השבחת קרקעות והובלת תוכניות עד שלב העלייה לקרקע. ליווי בעלי קרקע ויזמים בשרון ובמרכז.',
      summary: 'אפיק הנחל מקדמת תוכניות נדל"ן ומובילה ייזום של פרויקטים חדשים: מבדיקת הפוטנציאל התכנוני של הקרקע, דרך שינויי ייעוד והשבחה, ועד לשלב העלייה לקרקע ושיווק הפרויקט. השירות מיועד לבעלי קרקע שרוצים למצות את הפוטנציאל של הנכס, וליזמים שמחפשים שותף עם ניסיון בקרקעות.',
      sections: [
        { h2: 'מה אנחנו עושים בפועל', bullets: [
          '**בדיקת היתכנות תכנונית** — מה הקרקע יכולה להפוך להיות לפי התב"ע הקיימת, תוכניות המתאר והמגמות באזור.',
          '**קידום תוכניות ושינויי ייעוד** — הובלת התהליך מול הוועדות והיועצים (אדריכל, שמאי, יועץ תנועה, עו"ד).',
          '**השבחת קרקע** — הגדלת זכויות, שינוי שימושים ואיחוד וחלוקה, כשזה מתאים.',
          '**מבנה עסקה** — מכירה, עסקת קומבינציה, שיתוף פעולה עם חברת בנייה או קבוצת רכישה — לפי מה שנכון לבעל הקרקע.',
          '**ליווי עד עלייה לקרקע** — מהאישורים ועד תחילת הביצוע, ושיווק הפרויקט בהמשך.',
        ] },
        { h2: 'למי זה מתאים', bullets: ['**בעלי קרקע** — עם מגרש או שדה שיש לו פוטנציאל תכנוני, שרוצים להשביח לפני שמוכרים או להיכנס לשותפות.', '**יורשים** — שקיבלו קרקע ולא בטוחים מה נכון לעשות איתה.', '**יזמים וחברות בנייה** — שמחפשים קרקע מתאימה או שותף עם היכרות עמוקה עם השרון.'] },
        { h2: 'איך עובד תהליך ייזום', steps: [
          '**איתור ובדיקה** — נסח טאבו, תב"ע, זכויות קיימות, מגבלות (שימור, תשתיות, ייעודים גובלים).',
          '**תכנון ראשוני** — מה ניתן לבקש, כמה יחידות/שטח, ומה הסיכוי הריאלי.',
          '**כלכלה של הפרויקט** — עלויות, מיסוי (מס שבח, היטל השבחה), לוח זמנים ורווחיות.',
          '**קידום התוכנית** — הגשה לוועדה, תיאומים, התנגדויות, אישור.',
          '**רישוי** — היתרי בנייה.',
          '**ביצוע ושיווק** — בחירת קבלן, פיקוח, ושיווק הדירות או המגרשים.',
        ] },
        { h2: 'איפה', paras: ['הוד השרון, כפר סבא, רעננה, הרצליה, רמת השרון והשרון כולו, וכן המרכז. אלה אזורים עם ביקוש גבוה, מלאי קרקע מוגבל ותוכניות מתאר שמכתיבות איפה תהיה הבנייה הבאה — בדיוק המקום שבו ידע תכנוני שווה כסף.'] },
        { h2: 'למה איתנו', paras: ['ישראל בן יהודה מוביל קידום תוכניות נדל"ן — שינויי ייעוד והשבחות — כבר שנים, ומייצג בעלי קרקע מול חברות בנייה מהמובילות בישראל. אנחנו מסתכלים על הקרקע כמו יזם, ומייצגים אתכם כמו שותף.'] },
      ],
      faq: [
        { q: 'מה עושה חברת יזמות נדל"ן?', a: 'חברת יזמות נדל"ן מזהה קרקע או נכס עם פוטנציאל, מקדמת את התכנון והרישוי, מארגנת את המימון והביצוע, ומשווקת את התוצר — דירות, מגרשים או שטחי מסחר. היזם נושא בסיכון ובאחריות הכוללת, ומרוויח מהפער בין העלות לשווי המוגמר.' },
        { q: 'כמה זמן לוקח שינוי ייעוד?', a: 'בדרך כלל שנים, לא חודשים. הזמן תלוי בסוג התוכנית (מקומית או מחוזית), במורכבות, בהתנגדויות ובעומס בוועדות. לכן בדיקת היתכנות ריאלית לפני שמתחילים חוסכת שנים של ציפייה.' },
        { q: 'האם כדאי למכור את הקרקע עכשיו או להשביח קודם?', a: 'זו השאלה המרכזית של כל בעל קרקע. השבחה יכולה להעלות משמעותית את השווי, אבל דורשת זמן, השקעה וסבלנות, ולעיתים כדאי לשלב — למכור חלק או להיכנס לעסקת קומבינציה. אנחנו עוזרים להחליט על בסיס מספרים, לא תחושות.' },
        { q: 'מה ההבדל בין יזם לקבלן?', a: 'היזם הוא בעל הפרויקט: הוא רוכש או מארגן את הקרקע, מקדם תכנון ומימון ומוכר את התוצר. הקבלן מבצע את הבנייה עבור היזם לפי חוזה. אותה חברה יכולה לשמש בשני התפקידים, אבל האחריות והסיכון שונים.' },
      ],
    },
    en: {
      h1: 'Real estate development and plan promotion — from raw land to breaking ground', cardTitle: 'Development & plan promotion', serviceType: 'Real estate development',
      metaTitle: 'Real Estate Development in the Sharon: Plan Promotion, Rezoning & Land Improvement | Afik Hanahal',
      description: 'Developing new projects and promoting real estate plans: rezoning, land improvement and leading schemes up to breaking ground. Supporting landowners and developers in the Sharon and Central Israel.',
      summary: 'Afik Hanahal promotes real estate plans and leads the development of new projects: from assessing the planning potential of a plot, through rezoning and improvement, to breaking ground and marketing the project. It is for landowners who want to realise the full potential of their asset and for developers seeking a partner with deep land experience.',
      sections: [
        { h2: 'What we actually do', bullets: ['**Planning feasibility** — what the land can become under the current zoning plan, master plans and area trends.', '**Promoting plans and rezoning** — leading the process with the committees and consultants (architect, appraiser, traffic consultant, lawyer).', '**Land improvement** — increasing rights, changing uses, consolidation and re-parcelling where suitable.', '**Deal structure** — sale, combination deal, cooperation with a builder or a purchase group — whatever is right for the owner.', '**Support to ground-breaking** — from approvals to the start of construction, then marketing the project.'] },
        { h2: 'Who it is for', bullets: ['**Landowners** with a plot or field that has planning potential, who want to improve before selling or enter a partnership.', '**Heirs** who received land and are unsure what to do with it.', '**Developers and builders** looking for suitable land or a partner who knows the Sharon.'] },
        { h2: 'How a development process works', steps: ['**Sourcing and checks** — Tabu extract, zoning plan, existing rights, constraints.', '**Preliminary planning** — what can be requested, how many units / how much floor area, realistic odds.', '**Project economics** — costs, taxation (capital gains, betterment levy), timeline and profitability.', '**Plan promotion** — submission, coordination, objections, approval.', '**Permits** — building permits.', '**Construction and marketing** — contractor selection, supervision, and selling the units or plots.'] },
        { h2: 'Where', paras: ['Hod Hasharon, Kfar Saba, Ra\'anana, Herzliya, Ramat Hasharon and the whole Sharon, plus Central Israel — high demand, limited land supply and master plans that dictate where the next construction will be. Exactly where planning knowledge is worth money.'] },
        { h2: 'Why us', paras: ['Israel Ben-Yehuda has been leading real estate plan promotion — rezoning and improvement — for years, representing landowners opposite Israel\'s leading construction companies. We look at land like a developer and represent you like a partner.'] },
      ],
      faq: [
        { q: 'What does a real estate development company do?', a: 'It identifies land or property with potential, promotes planning and permits, organises financing and construction, and markets the result — apartments, plots or commercial space. The developer carries the overall risk and responsibility and earns the gap between cost and finished value.' },
        { q: 'How long does rezoning take?', a: 'Usually years, not months. It depends on the plan type (local or district), complexity, objections and committee workload. A realistic feasibility check before starting saves years of waiting.' },
        { q: 'Should I sell my land now or improve it first?', a: 'This is the central question for every landowner. Improvement can raise value significantly but takes time, investment and patience; sometimes a mix is best — selling part or entering a combination deal. We help decide based on numbers, not feelings.' },
        { q: 'What is the difference between a developer and a contractor?', a: 'The developer owns the project: acquires or organises the land, promotes planning and financing and sells the product. The contractor builds for the developer under contract. One company can do both, but the responsibility and risk differ.' },
      ],
    },
  },
  {
    slug: 'sell-your-property', cta: 'sell', updated: U,
    related: { services: ['rent-your-property', 'land-brokerage', 'project-marketing'], areas: ['hod-hasharon', 'kfar-saba', 'raanana', 'herzliya'], guides: ['how-to-sell-property', 'property-valuation'], glossary: ['exclusivity', 'capital-gains-tax', 'memorandum-of-understanding', 'appraiser', 'caveat'] },
    he: {
      h1: 'מכירת נכס בשרון — שיווק דירות, בתים ומגרשים', cardTitle: 'מכירת נכס / שיווק למכירה', serviceType: 'שיווק נכסים למכירה',
      metaTitle: 'רוצים למכור נכס בהוד השרון, כפר סבא או רעננה? שיווק ומכירה | אפיק הנחל',
      description: 'מכירת דירה, בית פרטי או מגרש בשרון: הערכת שווי, הכנת הנכס, שיווק ממוקד, סינון רוכשים, ניהול משא ומתן וליווי עד החוזה והרישום. שיחת ייעוץ ראשונה ללא עלות.',
      summary: 'אפיק הנחל משווקת ומוכרת דירות, בתים פרטיים, צמודי קרקע ומגרשים בהוד השרון, כפר סבא, רעננה, הרצליה ובכל השרון. התהליך מתחיל בהערכת שווי ותוכנית שיווק, ממשיך בסינון רוכשים ובניהול משא ומתן, ומסתיים בליווי חוזי ובהשלמת הרישום.',
      sections: [
        { h2: 'מה מקבלים', bullets: ['**הערכת שווי ריאלית** — על בסיס עסקאות דומות, מצב הנכס והביקוש בשכונה, לא על בסיס משאלות לב.', '**תוכנית שיווק** — צילום, ניסוח, ערוצי פרסום ופנייה ישירה למאגר רוכשים ומשקיעים.', '**סינון רוכשים** — הצגת הנכס רק לרוכשים רלוונטיים ובעלי יכולת.', '**ניהול משא ומתן** — כדי להגיע למחיר הנכון ולתנאים בטוחים.', '**ליווי חוזי** — עבודה עם עורך הדין שלכם עד החתימה, וליווי עד להעברת הזכויות.'] },
        { h2: 'למי זה מתאים', bullets: ['בעלי דירה או בית שרוצים למכור במחיר נכון ובזמן סביר.', 'משפרי דיור שצריכים לתזמן מכירה וקנייה.', 'יורשים שמוכרים נכס משותף.', 'בעלי מגרש או צמוד קרקע בשרון.'] },
        { h2: 'איך זה עובד', steps: ['שיחה ראשונה וביקור בנכס.', 'הערכת שווי ותמונת מיסוי (מס שבח, אם רלוונטי).', 'הכנת הנכס והחומרים לשיווק.', 'שיווק, סיורים ומשוב שוטף.', 'משא ומתן, זיכרון דברים והסכם מכר.', 'ליווי עד להשלמת העברת הזכויות.'] },
        { h2: 'שבעה דברים שאנחנו בודקים לפני שמשווקים נכס', bullets: ['רישום הזכויות (טאבו / חברה משכנת / רמ"י) והאם יש הערות אזהרה או שעבודים.', 'התאמה בין המצב בפועל להיתר — חריגות בנייה, תוספות ללא היתר.', 'מיסוי צפוי למוכר — האם יש פטור ממס שבח.', 'המצב הפיזי ומה כדאי לתקן לפני צילום.', 'עסקאות אחרונות בסביבה והיצע מתחרה.', 'קהל היעד — משפחות, משקיעים, משפרי דיור — והמסר המתאים לכל אחד.', 'לוח הזמנים שלכם — ומה זה אומר על אסטרטגיית המחיר.'] },
        { h2: 'איפה', paras: ['הוד השרון, כפר סבא, רעננה, הרצליה, רמת השרון, נתניה והשרון כולו. הבסיס שלנו בהוד השרון, והיכרות יומיומית עם השכונות והביקושים.'] },
      ],
      faq: [
        { q: 'מי יכול לעזור לי למכור בית בהוד השרון?', a: 'חברת שיווק ותיווך מקומית שמכירה את השכונות ואת הרוכשים הפעילים. אפיק הנחל פועלת מהוד השרון ומלווה מכירת דירות, בתים ומגרשים בכל השרון — מהערכת שווי ועד להשלמת ההעברה.' },
        { q: 'כמה עולה שירות תיווך במכירה?', a: 'בישראל מקובל לגבות עמלה באחוזים ממחיר המכירה, שנקבעת בהסכם תיווך בכתב לפני תחילת העבודה. נשמח להציג הצעה מסודרת אחרי ביקור בנכס.' },
        { q: 'מה צריך להכין לפני שמוכרים נכס?', a: 'נסח טאבו או אישור זכויות, היתר הבנייה ותשריט, אישורי מסים קודמים אם יש, ופרטים על ועד הבית ותשלומים שוטפים. אנחנו עוברים על הכול לפני הפרסום.' },
        { q: 'האם כדאי לשפץ לפני מכירה?', a: 'תיקונים קטנים, ניקיון וסידור כמעט תמיד משתלמים; שיפוץ גדול לרוב לא מחזיר את עצמו. נמליץ אחרי ביקור מה כדאי ומה לא.' },
      ],
    },
    en: {
      h1: 'Selling a property in the Sharon — apartments, houses and plots', cardTitle: 'Sell your property', serviceType: 'Property sales marketing',
      metaTitle: 'Selling a Property in Hod Hasharon, Kfar Saba or Ra\'anana? Marketing & Sales | Afik Hanahal',
      description: 'Selling an apartment, house or plot in the Sharon: valuation, preparation, targeted marketing, buyer screening, negotiation and support through contract and registration. Free first consultation.',
      summary: 'Afik Hanahal markets and sells apartments, houses, detached homes and plots in Hod Hasharon, Kfar Saba, Ra\'anana, Herzliya and across the Sharon. The process starts with a valuation and a marketing plan, continues with buyer screening and negotiation, and ends with legal support through the transfer of title.',
      sections: [
        { h2: 'What you get', bullets: ['**A realistic valuation** — based on comparable deals, condition and neighbourhood demand.', '**A marketing plan** — photography, copy, channels and direct outreach to our buyer and investor base.', '**Buyer screening** — showings only to relevant, capable buyers.', '**Negotiation** — for the right price and safe terms.', '**Contract support** — with your lawyer to signing, and through the transfer of rights.'] },
        { h2: 'Who it is for', bullets: ['Owners who want to sell at the right price in reasonable time.', 'Upgraders who must time a sale and a purchase.', 'Heirs selling a jointly owned property.', 'Owners of plots or detached homes in the Sharon.'] },
        { h2: 'How it works', steps: ['First call and visit.', 'Valuation and tax picture (capital gains, if relevant).', 'Preparing the property and materials.', 'Marketing, showings and ongoing feedback.', 'Negotiation, memorandum and sale agreement.', 'Support through completion.'] },
        { h2: 'Seven things we check before marketing a property', bullets: ['Title registration (Tabu / housing company / ILA) and any caveats or liens.', 'Match between the actual state and the permit — unpermitted additions.', 'The seller\'s expected tax — is there a capital gains exemption.', 'Physical condition and what is worth fixing before photos.', 'Recent deals nearby and competing supply.', 'The target audience — families, investors, upgraders — and the right message for each.', 'Your timeline — and what it means for pricing strategy.'] },
        { h2: 'Where', paras: ['Hod Hasharon, Kfar Saba, Ra\'anana, Herzliya, Ramat Hasharon, Netanya and the whole Sharon. We are based in Hod Hasharon with day-to-day knowledge of the neighbourhoods and demand.'] },
      ],
      faq: [
        { q: 'Who can help me sell a house in Hod Hasharon?', a: 'A local marketing and brokerage company that knows the neighbourhoods and the active buyers. Afik Hanahal works from Hod Hasharon and handles sales of apartments, houses and plots across the Sharon — from valuation to completion.' },
        { q: 'How much does brokerage cost when selling?', a: 'In Israel a percentage fee of the sale price is customary, set in a written brokerage agreement before work starts. We will present a clear proposal after visiting the property.' },
        { q: 'What should I prepare before selling?', a: 'Tabu extract or rights confirmation, the building permit and plan, previous tax confirmations if any, and details on the building committee and running costs. We review everything before publishing.' },
        { q: 'Should I renovate before selling?', a: 'Small repairs, cleaning and staging almost always pay off; a major renovation usually does not. We will advise after a visit.' },
      ],
    },
  },
  {
    slug: 'rent-your-property', cta: 'rent', updated: U,
    related: { services: ['sell-your-property', 'land-investment'], areas: ['hod-hasharon', 'kfar-saba', 'raanana', 'herzliya'], guides: ['property-valuation', 'how-to-sell-property'], glossary: ['yield', 'exclusivity'] },
    he: {
      h1: 'השכרת נכס בשרון — שיווק נכסים להשכרה ומציאת שוכרים', cardTitle: 'השכרת נכס', serviceType: 'שיווק נכסים להשכרה',
      metaTitle: 'רוצים להשכיר נכס בשרון? שיווק להשכרה ומציאת שוכר מתאים | אפיק הנחל',
      description: 'שיווק דירות, בתים ונכסים מסחריים להשכרה בהוד השרון, כפר סבא, רעננה והרצליה: קביעת שכר דירה ריאלי, פרסום, סינון שוכרים וליווי עד חתימת החוזה.',
      summary: 'אפיק הנחל משווקת נכסים להשכרה בשרון — דירות, בתים פרטיים ונכסים מסחריים — ועוזרת לבעלי נכסים למצוא שוכר מתאים במהירות ובביטחון: תמחור, פרסום, סינון ובדיקת שוכרים, וליווי עד חוזה שכירות מסודר.',
      sections: [
        { h2: 'מה כולל השירות', bullets: ['**קביעת שכר דירה ריאלי** לפי הביקוש בשכונה ומצב הנכס.', '**הכנת הנכס לשיווק** — צילום, ניסוח מודעה, הדגשת היתרונות.', '**פרסום ושיווק** — בערוצים המתאימים ובפנייה ישירה למחפשי דיור.', '**סינון שוכרים** — התאמה, יכולת כלכלית וערבויות.', '**ליווי לחוזה** — עד חתימה על חוזה שכירות מסודר ומסירת הנכס.'] },
        { h2: 'למי זה מתאים', bullets: ['בעלי דירה להשקעה שרוצים שוכר יציב.', 'בעלי בית שעוברים דירה או יוצאים לרילוקיישן.', 'בעלי נכס מסחרי (חנות, משרד, מחסן) בשרון.', 'יורשים שמחזיקים נכס ולא רוצים למכור עדיין.'] },
        { h2: 'איך זה עובד', steps: ['שיחה וביקור בנכס.', 'קביעת מחיר ואסטרטגיית שיווק.', 'פרסום, סיורים וסינון.', 'בדיקת השוכר וערבויות.', 'חוזה שכירות ומסירה.'] },
        { h2: 'איפה', paras: ['הוד השרון, כפר סבא, רעננה, הרצליה, רמת השרון והשרון כולו.'] },
      ],
      faq: [
        { q: 'כמה זמן לוקח למצוא שוכר?', a: 'נכס מתומחר נכון ומוצג היטב בשרון נסגר לרוב תוך שבועות ספורים. תמחור גבוה מדי הוא הסיבה הנפוצה ביותר לנכס ש"עומד".' },
        { q: 'איך בודקים שוכר?', a: 'התאמה לנכס, יכולת כלכלית (תלושי שכר או אישורי הכנסה), ממליצים מבעלי דירה קודמים, וערבויות מתאימות — ערבות בנקאית, ערבים או שטר חוב, לפי סוג הנכס.' },
        { q: 'מה צריך להיות בחוזה שכירות?', a: 'תקופה ואופציה, שכר דירה ומנגנון עדכון, ערבויות, אחריות לתיקונים, תשלומים שוטפים (ועד, ארנונה), ותנאי יציאה. מומלץ להיעזר בעורך דין; אנחנו מלווים את התהליך.' },
      ],
    },
    en: {
      h1: 'Renting out a property in the Sharon — marketing rentals and finding tenants', cardTitle: 'Rent out your property', serviceType: 'Rental marketing',
      metaTitle: 'Renting Out a Property in the Sharon? Rental Marketing & Tenant Search | Afik Hanahal',
      description: 'Marketing apartments, houses and commercial property for rent in Hod Hasharon, Kfar Saba, Ra\'anana and Herzliya: realistic rent, advertising, tenant screening and support to a signed lease.',
      summary: 'Afik Hanahal markets rental properties in the Sharon — apartments, houses and commercial space — and helps owners find the right tenant quickly and safely: pricing, advertising, tenant screening and checks, and support to a proper lease.',
      sections: [
        { h2: 'What the service includes', bullets: ['**Realistic rent** based on neighbourhood demand and condition.', '**Preparing the property** — photos, listing copy, highlighting advantages.', '**Advertising and marketing** — in the right channels and direct outreach.', '**Tenant screening** — fit, financial capacity and guarantees.', '**Lease support** — to a signed lease and handover.'] },
        { h2: 'Who it is for', bullets: ['Investment apartment owners who want a stable tenant.', 'Homeowners moving or relocating.', 'Commercial property owners (shop, office, warehouse) in the Sharon.', 'Heirs holding a property they do not want to sell yet.'] },
        { h2: 'How it works', steps: ['Call and visit.', 'Pricing and marketing strategy.', 'Advertising, showings and screening.', 'Tenant checks and guarantees.', 'Lease and handover.'] },
        { h2: 'Where', paras: ['Hod Hasharon, Kfar Saba, Ra\'anana, Herzliya, Ramat Hasharon and the whole Sharon.'] },
      ],
      faq: [
        { q: 'How long does it take to find a tenant?', a: 'A correctly priced, well presented property in the Sharon usually rents within a few weeks. Overpricing is the most common reason a property "sits".' },
        { q: 'How do you screen tenants?', a: 'Fit for the property, financial capacity (pay slips or income confirmations), references from previous landlords, and suitable guarantees — bank guarantee, guarantors or a promissory note, depending on the property.' },
        { q: 'What should a lease include?', a: 'Term and option, rent and adjustment mechanism, guarantees, repair responsibility, running costs (committee, municipal tax) and exit terms. Use a lawyer; we support the process.' },
      ],
    },
  },
  {
    slug: 'land-investment', cta: 'buy', updated: U,
    related: { services: ['land-brokerage', 'real-estate-development'], areas: ['sharon-region', 'hod-hasharon'], guides: ['agricultural-land-investment', 'land-due-diligence-checklist', 'rezoning-process'], glossary: ['agricultural-land', 'private-land', 'rezoning', 'purchase-tax', 'yield', 'district-committee'] },
    he: {
      h1: 'השקעה בקרקע בשרון — ליווי משקיעים בקרקעות עם פוטנציאל', cardTitle: 'השקעה בקרקעות', serviceType: 'ליווי השקעות בקרקע',
      metaTitle: 'קרקע להשקעה בשרון: איתור, בדיקה וליווי משקיעים | אפיק הנחל',
      description: 'ליווי משקיעים ברכישת קרקעות פרטיות בשרון ובמרכז: איתור קרקעות בשלבי תכנון, בדיקת ייעוד וסיכונים, מיסוי, ומחירי כניסה נגישים. בלי הבטחות — עם בדיקות.',
      summary: 'אפיק הנחל מלווה משקיעים שמחפשים קרקע פרטית עם פוטנציאל השבחה בשרון ובמרכז. אנחנו מאתרים קרקעות באזורי ביקוש ובשלבי תכנון, בודקים ייעוד, זכויות וסיכונים, מציגים את תמונת המיסוי, ומלווים את הרכישה עד לרישום. השקעה בקרקע היא השקעה לטווח ארוך — ואנחנו אומרים את זה מראש.',
      sections: [
        { h2: 'מה כולל הליווי', bullets: ['**איתור קרקעות** — פרטיות, בשלבי תכנון או בסמוך להרחבות עירוניות מתוכננות.', '**בדיקת נאותות** — תב"ע, ייעוד, זכויות, בעלות, שעבודים, תוכניות מתאר וסיכונים.', '**תמונת מיסוי** — מס רכישה, ומה צפוי במכירה (מס שבח, היטל השבחה).', '**מבנה השקעה** — לבד, בשותפות או בקבוצה, לפי הסכום ואופק ההשקעה.', '**ליווי לרכישה** — משא ומתן, ליווי משפטי ורישום.'] },
        { h2: 'למי זה מתאים', bullets: ['משקיעים שמבינים שקרקע היא השקעה לטווח של שנים, לא חודשים.', 'מי שמחפש כניסה במחיר נגיש לשוק הנדל"ן, במקום דירה שנייה.', 'משפחות שרוצות להחזיק מגרש לבנייה עתידית.'] },
        { h2: 'מה אנחנו בודקים לפני שאנחנו מציגים קרקע למשקיע', bullets: ['ייעוד נוכחי ומה התוכניות באזור אומרות עליו.', 'האם הקרקע פרטית (טאבו) או של רמ"י, ומה זה אומר על הזכויות.', 'מרחק מהשטח הבנוי ומהתשתיות — ככל שקרוב יותר, הסיכוי לפיתוח גבוה יותר.', 'מגבלות: שימור, תשתיות לאומיות, שטחים פתוחים, רצועות דרך.', 'מבנה הבעלות — מושע (שותפים רבים) לעומת חלקה נפרדת.', 'המחיר ביחס לעסקאות דומות, ולא ביחס ל"פוטנציאל".'] },
        { h2: 'סיכונים שצריך להכיר', paras: ['קרקע חקלאית עלולה להישאר חקלאית שנים רבות; תוכניות משתנות; שינוי ייעוד כרוך במסים ובהיטלים; ונזילות נמוכה — לא תמיד קל למכור מהר. השקעה טובה מתחילה בהבנת הסיכונים, לא בהתעלמות מהם.'] },
      ],
      faq: [
        { q: 'מה חשוב לבדוק לפני השקעה בקרקע?', a: 'ייעוד ותב"ע, בעלות ורישום (טאבו או רמ"י), שעבודים והערות אזהרה, מגבלות תכנוניות, מרחק מהבינוי הקיים, מבנה הבעלות (מושע), המיסוי הצפוי, והמחיר ביחס לעסקאות דומות. לעולם לא לקנות על בסיס הבטחה לשינוי ייעוד.' },
        { q: 'האם קרקע חקלאית היא השקעה טובה?', a: 'לפעמים — כשהיא צמודה לאזור בנוי עם ביקוש, כשיש תוכניות מתאר שמצביעות על פיתוח, וכשאופק ההשקעה ארוך (שנים רבות). לרוב הקרקעות החקלאיות בישראל אין תוכנית לשינוי ייעוד, ולכן הבדיקה קובעת הכול.' },
        { q: 'כמה כסף צריך כדי להשקיע בקרקע?', a: 'תלוי בייעוד, במיקום ובשטח. יש עסקאות במאות אלפי שקלים ויש במיליונים; קבוצות רכישה מאפשרות לעיתים כניסה בסכום נמוך יותר. חשוב לחשב גם מס רכישה, שכר טרחה ועלויות בדיקה.' },
      ],
    },
    en: {
      h1: 'Land investment in the Sharon — guiding investors to land with potential', cardTitle: 'Land investment', serviceType: 'Land investment advisory',
      metaTitle: 'Investment Land in the Sharon: Sourcing, Due Diligence & Investor Support | Afik Hanahal',
      description: 'Supporting investors buying private land in the Sharon and Central Israel: land at planning stages, zoning and risk checks, taxation and accessible entry prices. No promises — checks.',
      summary: 'Afik Hanahal supports investors looking for private land with improvement potential in the Sharon and Central Israel. We source land in demand areas and at planning stages, check designation, rights and risks, present the tax picture and support the purchase through registration. Land is a long-term investment — and we say so up front.',
      sections: [
        { h2: 'What the support includes', bullets: ['**Sourcing** — private land, at planning stages or near planned urban expansion.', '**Due diligence** — zoning plan, designation, rights, ownership, liens, master plans and risks.', '**Tax picture** — purchase tax, and what to expect on sale (capital gains, betterment levy).', '**Investment structure** — alone, in partnership or in a group, by budget and horizon.', '**Purchase support** — negotiation, legal support and registration.'] },
        { h2: 'Who it is for', bullets: ['Investors who understand land is a multi-year investment.', 'Those seeking an accessible entry into real estate instead of a second apartment.', 'Families who want to hold a plot for future building.'] },
        { h2: 'What we check before showing land to an investor', bullets: ['Current designation and what the area plans say about it.', 'Private land (Tabu) or Israel Land Authority land, and what that means for rights.', 'Distance from the built-up area and infrastructure — the closer, the higher the development odds.', 'Constraints: conservation, national infrastructure, open spaces, road corridors.', 'Ownership structure — undivided shares versus a separate parcel.', 'Price versus comparable deals, not versus "potential".'] },
        { h2: 'Risks to know', paras: ['Agricultural land may stay agricultural for many years; plans change; rezoning triggers taxes and levies; and liquidity is low. A good investment starts with understanding the risks, not ignoring them.'] },
      ],
      faq: [
        { q: 'What should I check before investing in land?', a: 'Designation and zoning plan, ownership and registration (Tabu or ILA), liens and caveats, planning constraints, distance from existing development, ownership structure, expected taxation, and price versus comparable deals. Never buy on a promise of rezoning.' },
        { q: 'Is agricultural land a good investment?', a: 'Sometimes — when it adjoins a built-up area with demand, when master plans point to development, and when the horizon is long (many years). Most agricultural land in Israel has no rezoning plan, so the checks decide everything.' },
        { q: 'How much money do I need to invest in land?', a: 'It depends on designation, location and size. Deals range from hundreds of thousands to millions of shekels; purchase groups sometimes allow a lower entry. Budget purchase tax, fees and due-diligence costs too.' },
      ],
    },
  },
  {
    slug: 'project-marketing', cta: 'project', updated: U,
    related: { services: ['real-estate-development', 'sell-your-property'], areas: ['hod-hasharon', 'sharon-region'], guides: ['what-is-real-estate-development', 'how-to-sell-property'], glossary: ['developer', 'boutique-project', 'purchase-group', 'detached-house'] },
    he: {
      h1: 'שיווק פרויקטים ובתי יוקרה בשרון', cardTitle: 'שיווק פרויקטים ובתי יוקרה', serviceType: 'שיווק פרויקטים',
      metaTitle: 'שיווק פרויקטים חדשים ובתי יוקרה בשרון | אפיק הנחל',
      description: 'שיווק פרויקטים למגורים, מגרשים בפרויקט ובתי יוקרה בשרון: אסטרטגיית מכירה, תמחור, חומרי שיווק, ניהול מאגר לקוחות וסגירת עסקאות עבור יזמים ובעלי נכסים.',
      summary: 'אפיק הנחל משווקת פרויקטים חדשים ובתי יוקרה בשרון עבור יזמים, קבוצות רכישה ובעלי נכסים: מאסטרטגיית המכירה והתמחור, דרך חומרי השיווק וניהול הפניות, ועד סגירת העסקאות. הבסיס: היכרות יומיומית עם הרוכשים והמשקיעים באזור.',
      sections: [
        { h2: 'מה כולל השירות', bullets: ['**אסטרטגיית שיווק ותמחור** — לכל שלב בפרויקט: פריסייל, בנייה, מסירה.', '**חומרי שיווק** — מסרים, מפרט, הדמיות ותוכן לערוצים הדיגיטליים.', '**ניהול פניות ולידים** — מענה מהיר, סינון ותיאום פגישות.', '**סגירת עסקאות** — ליווי הרוכש עד החתימה, בתיאום עם עורכי הדין של הפרויקט.', '**דיווח שוטף** ליזם — קצב מכירות, משוב מהשוק ותיקוני מסלול.'] },
        { h2: 'למי זה מתאים', bullets: ['יזמים עם פרויקט מגורים או מגרשים בשרון ובמרכז.', 'קבוצות רכישה שצריכות לשווק יחידות נותרות.', 'בעלי בתי יוקרה וצמודי קרקע שדורשים שיווק דיסקרטי וממוקד.'] },
        { h2: 'איך זה עובד', steps: ['הכרת הפרויקט, המפרט והיעדים.', 'בניית אסטרטגיה ותמחור לכל שלב.', 'הפקת חומרים והשקה.', 'ניהול פניות, סיורים ומשא ומתן.', 'סגירה, דיווח ותיקוני מסלול.'] },
      ],
      faq: [
        { q: 'איך משווקים פרויקט מגורים?', a: 'מגדירים קהל יעד ומסר, מתמחרים לפי שלב הפרויקט והתחרות, מפיקים חומרים (הדמיות, מפרט, תוכן), משיקים בערוצים הנכונים, מנהלים את הפניות במהירות ובקפידה, וסוגרים עסקאות תוך דיווח שוטף ליזם. מעקב אחרי קצב המכירות מאפשר להתאים מחיר ומסרים בזמן.' },
        { q: 'מה ההבדל בין שיווק פרויקט לתיווך דירה?', a: 'שיווק פרויקט הוא תהליך מתמשך של עשרות יחידות עם אסטרטגיה, תמחור מדורג וניהול מאגר לקוחות; תיווך דירה הוא עסקה בודדת. שניהם דורשים היכרות עם הרוכשים באזור — אצלנו זה הבסיס.' },
      ],
    },
    en: {
      h1: 'Project and luxury home marketing in the Sharon', cardTitle: 'Project & luxury home marketing', serviceType: 'Project marketing',
      metaTitle: 'Marketing New Projects & Luxury Homes in the Sharon | Afik Hanahal',
      description: 'Marketing residential projects, project plots and luxury homes in the Sharon: sales strategy, pricing, marketing materials, lead management and closing for developers and owners.',
      summary: 'Afik Hanahal markets new projects and luxury homes in the Sharon for developers, purchase groups and owners: from sales strategy and pricing, through marketing materials and lead management, to closing. The base: day-to-day knowledge of the area\'s buyers and investors.',
      sections: [
        { h2: 'What the service includes', bullets: ['**Marketing and pricing strategy** for each stage: pre-sale, construction, delivery.', '**Marketing materials** — messaging, specifications, renders and digital content.', '**Lead management** — fast response, screening and meetings.', '**Closing** — accompanying the buyer to signing with the project\'s lawyers.', '**Regular reporting** to the developer — sales pace, market feedback and course corrections.'] },
        { h2: 'Who it is for', bullets: ['Developers with a residential or plot project in the Sharon and Central Israel.', 'Purchase groups needing to market remaining units.', 'Owners of luxury and detached homes requiring discreet, targeted marketing.'] },
        { h2: 'How it works', steps: ['Understanding the project, specification and goals.', 'Strategy and pricing per stage.', 'Materials and launch.', 'Leads, showings and negotiation.', 'Closing, reporting and adjustments.'] },
      ],
      faq: [
        { q: 'How do you market a residential project?', a: 'Define the audience and message, price by stage and competition, produce materials (renders, spec, content), launch in the right channels, manage leads fast and carefully, and close deals while reporting to the developer. Tracking sales pace lets you adjust price and messaging in time.' },
        { q: 'What is the difference between project marketing and apartment brokerage?', a: 'Project marketing is an ongoing process for dozens of units with strategy, staged pricing and a client database; apartment brokerage is a single deal. Both require knowing the area\'s buyers — for us that is the foundation.' },
      ],
    },
  },
  {
    // BUSINESS REVIEW: offered service per owner's confirmation (ייזום עם ביצוע ופיקוח). Scope, fee model and
    // any track record must be confirmed by Afik Hanahal before adding specifics. No project claims are made here.
    slug: 'project-management-supervision', cta: 'project', updated: U,
    related: { services: ['real-estate-development', 'land-brokerage', 'project-marketing'], areas: ['hod-hasharon', 'sharon-region', 'kfar-saba'], guides: ['construction-supervision', 'developer-vs-contractor', 'what-is-real-estate-development'], glossary: ['supervisor', 'contractor', 'building-permit', 'developer', 'building-rights'] },
    he: {
      h1: 'ניהול, ביצוע ופיקוח פרויקטים בשרון ובמרכז', cardTitle: 'ניהול, ביצוע ופיקוח פרויקטים', serviceType: 'ניהול ופיקוח פרויקטי בנייה',
      metaTitle: 'ניהול פרויקטים, ביצוע ופיקוח בנייה בשרון | אפיק הנחל',
      description: 'ניהול פרויקט בנייה מקצה לקצה בשרון ובמרכז: תכנון ורישוי, מכרז קבלנים, ניהול ביצוע ופיקוח צמוד על איכות, תקציב ולוח זמנים - לבעלי מגרשים, ליזמים ולמשפחות שבונות בית.',
      summary: 'אפיק הנחל מלווה בעלי מגרשים ויזמים בשרון ובמרכז מהרעיון ועד למסירה: בדיקת היתכנות, תכנון ורישוי, בחירת קבלן, ניהול הביצוע ופיקוח צמוד באתר. המטרה פשוטה - שהפרויקט ייבנה לפי התוכניות, בתקציב ובזמן, ושתהיה לכם כתובת אחת שאחראית על הכול.',
      sections: [
        { h2: 'מה כולל השירות', bullets: [
          '**בדיקת היתכנות** - זכויות בנייה, מגבלות תב"ע, אומדן עלויות ראשוני ולוח זמנים ריאלי, לפני שמתחייבים.',
          '**ניהול התכנון והרישוי** - תיאום אדריכל, קונסטרוקטור ויועצים, הגשה לוועדה המקומית וליווי עד היתר הבנייה.',
          '**מכרז קבלנים** - כתב כמויות, השוואת הצעות, בדיקת רישום וסיווג הקבלן, ניסוח חוזה עם אבני תשלום וערבויות.',
          '**ניהול ביצוע** - תיאום קבלנים וספקים, מעקב תקציב ולוח זמנים, טיפול בשינויים ובתוספות.',
          '**פיקוח צמוד** - ביקורות באתר בשלבים קריטיים (יסודות, זיון, איטום, מערכות), אישור חשבונות מול העבודה שבוצעה, יומן עבודה ודיווח שוטף.',
          '**מסירה ורישום** - קבלת העבודות, תיקוני ליקויים, טופס 4 ותעודת גמר, ואם רלוונטי - שיווק ומכירה של התוצר.',
        ] },
        { h2: 'למי זה מתאים', bullets: [
          '**משפחות שבונות בית פרטי** על מגרש שרכשו או ירשו, ורוצות מישהו שמנהל את הקבלן ולא להפך.',
          '**בעלי מגרש עם זכויות** לדו-משפחתי או לכמה יחידות, ששוקלים לבנות ולמכור במקום למכור את הקרקע.',
          '**יזמים ומשקיעים** שצריכים גורם מקומי מנוסה בשרון שינהל את הפרויקט מולם.',
          '**בעלי נכס בהשבחה** - תוספת יחידה, הרחבה או הריסה ובנייה מחדש.',
        ] },
        { h2: 'איך זה עובד', steps: [
          'פגישת היכרות ובדיקת המגרש או הנכס: זכויות, מצב תכנוני, יעדים ותקציב.',
          'הצעת ליווי מוגדרת: היקף השירות, שלבי העבודה ואופן התמחור - מסוכמים בכתב.',
          'תכנון ורישוי עד היתר, במקביל להכנת מכרז הקבלנים.',
          'בחירת קבלן וחתימת חוזה מבוסס כתב כמויות.',
          'ניהול הביצוע והפיקוח: ביקורות, אישורי תשלום, דיווח שוטף אליכם.',
          'מסירה, תיקונים, טופס 4 - ולפי הצורך שיווק ומכירה.',
        ] },
        { h2: 'למה לעבוד עם אפיק הנחל', paras: ['אנחנו מגיעים לניהול הפרויקט מהצד של הקרקע: אנחנו מכירים את הוועדות המקומיות בשרון, את התב"עות ואת שווי התוצר הסופי, ולכן ההחלטות בתכנון ובביצוע נבחנות גם מבחינת הכדאיות והשיווק - לא רק מבחינת ההנדסה. כשהפרויקט מיועד למכירה, אותו צוות שמלווה את הבנייה מלווה גם את השיווק.', 'היקף השירות ואופן התמחור נקבעים לכל פרויקט בנפרד, בהתאם לגודלו ולשלב שבו אתם נמצאים. נשמח לבדוק אתכם את הפרויקט ללא התחייבות.'] },
      ],
      faq: [
        { q: 'מה ההבדל בין ניהול פרויקט לפיקוח בנייה?', a: 'ניהול פרויקט מקיף את כל התהליך - תכנון, רישוי, מכרז, תקציב ולוח זמנים. פיקוח מתמקד בשלב הביצוע: בדיקה שהקבלן בונה לפי התוכניות והחוזה ואישור תשלומים. אצלנו אפשר לקבל את שניהם יחד או רק פיקוח.' },
        { q: 'כמה עולה ניהול ופיקוח פרויקט?', a: 'התמחור נקבע לפי היקף הפרויקט ושלבי הליווי - כאחוז מעלות הבנייה, כתשלום חודשי או כסכום קבוע לשלב. נגדיר זאת בהצעה כתובה אחרי בדיקת הפרויקט.' },
        { q: 'האם אתם גם הקבלן המבצע?', a: 'הביצוע נעשה באמצעות קבלנים רשומים שנבחרים במכרז עבור כל פרויקט. אנחנו מנהלים ומפקחים מטעמכם, כך שהאינטרס שלנו הוא שלכם - לא של הקבלן.' },
        { q: 'באילו אזורים אתם מנהלים פרויקטים?', a: 'בעיקר בערי השרון - הוד השרון, כפר סבא, רעננה, הרצליה ורמת השרון - ובמרכז הארץ.' },
      ],
    },
    en: {
      h1: 'Project management, execution and construction supervision in the Sharon', cardTitle: 'Project management & supervision', serviceType: 'Construction project management and supervision',
      metaTitle: 'Project Management, Execution & Construction Supervision in the Sharon | Afik Hanahal',
      description: 'End-to-end construction project management in the Sharon and Central Israel: planning and licensing, contractor tender, execution management and close supervision of quality, budget and schedule - for plot owners, developers and families building a home.',
      summary: 'Afik Hanahal accompanies plot owners and developers in the Sharon and Central Israel from idea to handover: feasibility, planning and licensing, contractor selection, execution management and close on-site supervision. The goal is simple - the project is built to the drawings, on budget and on time, with one address responsible for everything.',
      sections: [
        { h2: 'What the service includes', bullets: [
          '**Feasibility** - building rights, plan constraints, an initial cost estimate and a realistic schedule, before you commit.',
          '**Planning and licensing management** - coordinating the architect, structural engineer and consultants, submission to the local committee and support through to the building permit.',
          '**Contractor tender** - bill of quantities, bid comparison, checking the contractor\'s registration and classification, a contract with payment milestones and guarantees.',
          '**Execution management** - coordinating contractors and suppliers, tracking budget and schedule, handling changes and extras.',
          '**Close supervision** - site inspections at critical stages (foundations, reinforcement, waterproofing, systems), approving invoices against work done, site diary and regular reporting.',
          '**Handover and registration** - acceptance of works, defect repairs, Form 4 and certificate of completion, and where relevant marketing and sale of the product.',
        ] },
        { h2: 'Who it is for', bullets: [
          '**Families building a house** on a plot they bought or inherited, who want someone managing the contractor rather than the other way round.',
          '**Plot owners with rights** for a semi-detached pair or several units, considering building and selling instead of selling the land.',
          '**Developers and investors** who need an experienced local party in the Sharon to run the project for them.',
          '**Owners upgrading a property** - adding a unit, extending, or demolishing and rebuilding.',
        ] },
        { h2: 'How it works', steps: [
          'Introductory meeting and review of the plot or property: rights, planning status, goals and budget.',
          'A defined engagement proposal: scope, work stages and pricing - agreed in writing.',
          'Planning and licensing through to permit, in parallel with preparing the contractor tender.',
          'Contractor selection and a quantities-based contract.',
          'Execution management and supervision: inspections, payment approvals, regular reporting to you.',
          'Handover, repairs, Form 4 - and marketing and sale where needed.',
        ] },
        { h2: 'Why work with Afik Hanahal', paras: ['We come to project management from the land side: we know the Sharon\'s local committees, its plans and the value of the finished product, so planning and execution decisions are weighed for feasibility and marketability as well as engineering. When the project is for sale, the same team that accompanies construction accompanies the marketing.', 'Scope and pricing are set per project, according to its size and the stage you are at. We would be glad to review your project with you, without obligation.'] },
      ],
      faq: [
        { q: 'What is the difference between project management and construction supervision?', a: 'Project management covers the whole process - planning, licensing, tender, budget and schedule. Supervision focuses on execution: checking the contractor builds to the drawings and contract and approving payments. We offer both together or supervision alone.' },
        { q: 'How much does project management and supervision cost?', a: 'Pricing depends on project scope and the stages covered - a percentage of construction cost, a monthly fee or a fixed sum per stage. We define it in a written proposal after reviewing the project.' },
        { q: 'Are you also the building contractor?', a: 'Execution is carried out by registered contractors selected by tender for each project. We manage and supervise on your behalf, so our interest is yours - not the contractor\'s.' },
        { q: 'Which areas do you manage projects in?', a: 'Mainly the Sharon cities - Hod Hasharon, Kfar Saba, Ra\'anana, Herzliya and Ramat Hasharon - and Central Israel.' },
      ],
    },
  },
]
